Update upgrade.rst
mattermost/docs pull request #3879
Opened 2020-09-01 17:49 UTC by justinegeffen

Removed reference to RHEL 6 and Ubuntu 16.04.

2020-09-01 17:49 UTC, justinegeffen commented
@svelle, let me know what the commands are for the latest versions and I can add them. :)

2020-09-02 11:15 UTC, svelle commented
> @svelle, let me know what the commands are for the latest versions and I can add them. :)

Hey  @justinegeffen you can remove the `On Ubuntu 16.04 and RHEL 6` and just leave the rest as the command should work on every distro since then.

2020-09-02 11:16 UTC, svelle requested changes
If we remove this I think we should be good :)

2020-09-02 11:16 UTC, svelle commented on source/administration/upgrade.rst
>     On Ubuntu 16.04 and RHEL 7:
```suggestion
```

2020-09-02 11:16 UTC, svelle commented on source/administration/upgrade.rst
>     On Ubuntu 16.04 and RHEL 7:
```suggestion
```

2020-09-02 11:49 UTC, justinegeffen commented
@jasonblais, adding you for editorial review as Amy is on PTO. :)

2020-09-08 19:37 UTC, justinegeffen commented
@svelle, just confirming that we're good to go with this. :)

2020-09-08 20:43 UTC, svelle commented
> @svelle, just confirming that we're good to go with this. :)

Good to go from my end!

2020-09-08 20:47 UTC, merged