v1.36 Mobile Changelog
mattermost/docs pull request #3934
Opened 2020-09-24 19:31 UTC by amyblais

2020-09-24 19:31 UTC, amyblais commented on source/administration/mobile-changelog.md
> + - **Upgrade to server version v5.25 or later is required.** Support for server [Extended Support Release](https://docs.mattermost.com/administration/extended-support-release.html) (ESR) 5.19 has end
Update in app stores.

2020-10-08 14:17 UTC, enahum requested changes

2020-10-08 14:17 UTC, enahum commented on source/administration/mobile-changelog.md
> + - Server URL now autofills when opening the app from the mobile landing page.
I can assume this is the landing page of the webapp, but it's not very clear imho

2020-10-08 14:17 UTC, enahum commented on source/administration/mobile-changelog.md
> + - Fixed an issue where a hashtag (#) character added to an announcement banner caused the app to display a blanck screen.
```suggestion
 - Fixed an issue where a hashtag (#) character added to an announcement banner caused the app to display a blank screen.
```

2020-10-08 14:17 UTC, enahum commented on source/administration/mobile-changelog.md
> + - Fixed an issue where users were unable to join public channels via channel permalinks.
```suggestion
 - Fixed an issue where users were unable to join public channels via channel link.
```

2020-10-08 15:02 UTC, amyblais commented on source/administration/mobile-changelog.md
> + - **Upgrade to server version v5.25 or later is required.** Support for server [Extended Support Release](https://docs.mattermost.com/administration/extended-support-release.html) (ESR) 5.19 has end
Sounds good to me.

2020-10-08 17:23 UTC, enahum approved these changes

2020-10-08 20:38 UTC, esethna approved these changes

2020-10-15 23:00 UTC, merged