ES v5.28 docs
mattermost/docs pull request #3968
Opened 2020-10-08 23:47 UTC by esethna

2020-10-08 23:49 UTC, esethna commented
@amyblais can you help hook up the redirect from the in-product link to this docs page? https://mattermost.atlassian.net/browse/MM-28847

```
https://about.mattermost.com/default-notices/
```

2020-10-08 23:58 UTC, esethna commented
@justinegeffen the image and toc tree isn't appearing for some reason on the notices doc

2020-10-08 23:59 UTC, amyblais requested changes

2020-10-08 23:59 UTC, amyblais commented on source/administration/notices.rst
> +Mattermost is introducing in-product notices to keep users and adminstrators informed of the newest product improvements, features and releases.
```suggestion
Mattermost is introducing in-product notices to keep users and administrators informed of the newest product improvements, features and releases.
```

2020-10-08 23:59 UTC, amyblais commented on source/administration/notices.rst
> + .. image:: ../images/notices.png
Image doesn't show.

2020-10-08 23:59 UTC, amyblais commented on source/administration/notices.rst
> +Adminstrator Notices
```suggestion
Administrator Notices
```

2020-10-08 23:59 UTC, amyblais commented on source/administration/notices.rst
> +Administrator notices are used to inform System Admins when a new server version is available, or if a server upgrade is recommended due to ending support life cycles. System Admins may also recieve
```suggestion
Administrator notices are used to inform System Admins when a new server version is available, or if a server upgrade is recommended due to ending support life cycles. System Admins may also receive notices about recommended server configuration options to optimize the user experience of their deployment.
```

2020-10-08 23:59 UTC, amyblais commented on source/administration/notices.rst
> +Are notices enabled by-default?
```suggestion
Are notices enabled by default?
```

2020-10-08 23:59 UTC, amyblais commented on source/administration/notices.rst
> +Notices are enabled by-default for all Mattermost users. System Admins may choose to disable administrator or end user notices in the **System Console > Notices** page.
```suggestion
Notices are enabled by default for all Mattermost users. System Admins may choose to disable administrator or end user notices in the **System Console > Notices** page.
```

2020-10-08 23:59 UTC, amyblais commented on source/administration/notices.rst
> +No, the Mattermost server requires a connection to the internet to recieve notices.
```suggestion
No, the Mattermost server requires a connection to the internet to receive notices. 
```

2020-10-08 23:59 UTC, amyblais commented on source/administration/notices.rst
> +Notices will be used to raise awreness of new features as part of our monthly release cadence. Users will only recieve notices that apply to them specifically. For example, if a user is already runni
```suggestion
Notices will be used to raise awareness of new features as part of our monthly release cadence. Users will only receive notices that apply to them specifically. For example, if a user is already running the latest desktop app version, they will not receive a desktop upgrade notice.  
```

2020-10-08 23:59 UTC, amyblais commented on source/help/getting-started/configuring-notifications.rst
> +Desktop notifications are pop-ups that appear in the corner of your main monitor when using Chrome, Firefox, Edge, Safari, or the `Mattermost Desktop apps <https://mattermost.com/download/#mattermost
```suggestion
Desktop notifications are pop-ups that appear in the corner of your main monitor when using Chrome, Firefox, Edge, Safari, or the `Mattermost Desktop Apps <https://mattermost.com/download/#mattermostApps>`_. You can change the default preference to trigger desktop notifications for all messages sent in channels you're a member of, or turn them off entirely. You can also choose what sound plays when a desktop notification is triggered on supported browsers and the Mattermost Desktop Apps.
```

2020-10-09 11:14 UTC, justinegeffen commented on source/help/getting-started/configuring-notifications.rst
> +-  Configure desktop notifications in **Account Settings > Notifications > Desktop notifications > Send desktop notifications** and choose your sound selection.
```suggestion
-  Configure desktop notifications in **Account Settings > Notifications > Desktop Notifications > Send desktop notifications** and choose your sound selection.
```

2020-10-09 11:16 UTC, justinegeffen commented on source/administration/notices.rst
> +Notices will be used to raise awareness of new features as part of our monthly release cadence. Users will only receive notices that apply to them specifically. For example, if a user is already runn
```suggestion
Notices will be used to raise awareness of new features as part of our monthly release cadence. Users will only receive notices that specifically apply to them. For example, if a user is already running the latest Desktop App version, they will not receive an upgrade notice. 
```

2020-10-09 11:17 UTC, justinegeffen commented on source/administration/notices.rst
> +No, the Mattermost server requires a connection to the internet to receive notices.
```suggestion
No, the Mattermost server requires a connection to the internet to receive notices.
```

2020-10-09 12:28 UTC, justinegeffen commented on source/administration/notices.rst
> +Mattermost is introducing in-product notices to keep users and administrators informed of the newest product improvements, features and releases.
```suggestion
Mattermost in-product notices keep users and administrators informed of the newest product improvements, features, and releases.
```

2020-10-09 13:24 UTC, justinegeffen commented on source/administration/notices.rst
> +End user notices are used to inform users and Admins of new feature enhancements, and when new desktop versions are available. End User notices can be disabled in the **System Console > Notices** pag
```suggestion
End user notices are used to inform users and Admins of new feature enhancements and when new desktop versions are available. They can be disabled in **System Console > Notices**.
```

2020-10-09 13:25 UTC, justinegeffen commented on source/administration/notices.rst
> +Notices are enabled by default for all Mattermost users. System Admins may choose to disable administrator or end user notices in the **System Console > Notices** page.
```suggestion
Notices are enabled by default for all Mattermost users. System Admins may choose to disable administrator or end user notices in **System Console > Notices**.
```

2020-10-09 13:26 UTC, justinegeffen approved these changes

2020-10-10 12:26 UTC, justinegeffen commented
Docs for: https://github.com/mattermost/mattermost-server/pull/15316.

2020-10-12 15:07 UTC, amyblais commented
@esethna Will the In-Product Notices config settings be documented? ``AdminNoticesEnabled``, ``UserNoticesEnabled``, ``NoticesURL``, ``NoticesFetchFrequency``, and ``NoticesSkipCache``

2020-10-13 13:04 UTC, justinegeffen commented
@esethna, could you add this to the relevant guide's TOC so that it displays on the LHS and I can validate the preview? Thank you!

2020-10-13 14:59 UTC, esethna commented
@justinegeffen how do I do that?

2020-10-13 15:05 UTC, amyblais commented
@esethna You can update it by navigating to the TOC page, not sure if it would be https://docs.mattermost.com/guides/administrator.html or https://docs.mattermost.com/guides/user.html.

2020-10-13 15:15 UTC, esethna commented
@justinegeffen @amyblais done but I accidently committed directly to the v5.28-documentation branch

2020-10-13 16:44 UTC, justinegeffen commented
Awesome, thanks @esethna! So it's all rendering perfectly except the image and I'm not sure what the issue is. Here's a screenshot of how it renders in [preview](https://mattermost.github.io/docs/esethna/administration/notices.html) vs the code in the docs. 

![Screen Shot 2020-10-13 at 18 41 21](https://user-images.githubusercontent.com/4223530/95890407-0ffcc500-0d84-11eb-8e8f-9bdc0038c6e2.png)

<img width="337" alt="Screen Shot 2020-10-13 at 18 41 28" src="https://user-images.githubusercontent.com/4223530/95890414-11c68880-0d84-11eb-9bb0-375c614c3f64.png">

@amyblais, do you have any idea where the problem is? It all looks like it should work fine.

2020-10-13 17:10 UTC, amyblais commented
I'm unsure to be honest, will need to troubleshoot further.

@esethna Did we also want to include the missing config settings https://github.com/mattermost/docs/pull/3968#issuecomment-707177022?

2020-10-13 18:38 UTC, justinegeffen commented
I propose removing the screenshot for now so it doesn't block the docs, and we can add it back post-release. @esethna, does that work for you?

2020-10-13 18:41 UTC, esethna commented
@justinegeffen that's fine. I'd propose we merge as is as it may work on docs once merged. Let's just make sure to revisit after merge to get the screenshot working

2020-10-13 18:41 UTC, esethna commented
@amyblais adding now

2020-10-13 18:53 UTC, esethna commented
@amyblais config settings added, we are not documenting NoticesURL, NoticesFetchFrequency, and NoticesSkipCache because they are only used for testing

2020-10-14 13:12 UTC, merged