Ensure DB encoding is UTF-8
mattermost/docs pull request #4029
Opened 2020-10-23 07:31 UTC by DavidePrincipi

#### Summary

The default PostgreSQL DB encoding depends on the shell locale set at initialization time. 
As Mattermost might not work with other encodings, create the DB by setting the UTF-8 encoding explicitly.

#### Ticket Link

More details here:

- https://github.com/mattermost/docs/issues/3943
- https://github.com/NethServer/nethserver-mattermost/pull/56

2020-10-23 07:31 UTC, mattermod commented
Hello @DavidePrincipi,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

Per the [Mattermost Contribution Guide](https://developers.mattermost.com/contribute/getting-started/), we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**
Once you have signed the CLA, please comment with `/check-cla` and confirm that the CLA check is green.

This is a standard procedure for many open source projects.

Please let us know if you have any questions.

We are very happy to have you join our growing community! If you're not yet a member, please consider joining our [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets) to meet other contributors and discuss new opportunities with the core team.

2020-10-23 07:43 UTC, DavidePrincipi commented
/check-cla

2020-10-23 15:53 UTC, justinegeffen commented
Thank you for this, @DavidePrincipi! To confirm, should this also be updated for the RHEL 8 docs? Or is it just for RHEL 7?

2020-10-23 16:32 UTC, DavidePrincipi commented
...I guess the same applies to any PostgreSQL-based documentation, however I can't verify it. Do I have to fix them all anyway?

2020-10-23 17:05 UTC, justinegeffen commented
Thanks, @DavidePrincipi, that's great. I'll defer to @agnivade and @streamer45 in terms of verifying it. And then we'll have a clearer idea of the extent of the update. For now, though, I don't want to add unnecessary work so I'll await their feedback.

2020-10-27 04:55 UTC, agnivade requested changes
Thank you @DavidePrincipi for the change! Looks good to me, just one small thing to take care of.

2020-10-27 04:55 UTC, agnivade commented on source/install/install-rhel-7-postgresql.rst
> +10.  Create the Mattermost database with UTF-8 encoding.
We don't need to mention the UTF-8 part here. The command is all the user needs to execute.

2020-10-27 04:55 UTC, agnivade commented on source/install/install-rhel-8-postgresql.rst
> +8.  Create the Mattermost database with UTF-8 encoding.
Same as above.

2020-10-27 07:50 UTC, justinegeffen commented
Looks good to me editorially; agree with the suggestions made by @agnivade.

2020-10-27 09:08 UTC, agnivade approved these changes

2020-10-28 08:19 UTC, streamer45 approved these changes
Grazie @DavidePrincipi :)

@justinegeffen , @agnivade If you agree I think it makes sense to open a ticket to also update other postgres specific installation guides since this could be helpful on other distributions/systems as well.

2020-10-28 08:29 UTC, agnivade commented
Makes sense to me.

2020-11-02 19:58 UTC, justinegeffen approved these changes

2020-11-02 19:59 UTC, justinegeffen commented
Thanks, @streamer45! I do agree with that. I'll merge this PR and then create a HW ticket for the further update. :)

2020-11-02 19:59 UTC, merged