Update important-upgrade-notes.rst
mattermost/docs pull request #4058
Opened 2020-11-02 13:27 UTC by amyblais

For https://github.com/mattermost/mattermost-server/pull/15878. Will be added to the changelog once the text is reviewed/approved.

2020-11-02 15:20 UTC, reflog approved these changes

2020-11-03 23:55 UTC, esethna requested changes

2020-11-03 23:55 UTC, esethna commented on source/administration/important-upgrade-notes.rst
> +| v5.29.0                                            | A new ``ThreadAutoFollow`` setting was added to add support for thread auto following. This setting is enabled by default and may have an impact
```

A new configuration setting ``ThreadAutoFollow`` has been added to support `Collapsed Reply Threads <https://docs.google.com/presentation/d/1QSrPws3N8AMSjVyOKp15FKT7O0fGMSx8YidjSDS4Wng/edit#slide=id.g2f0aecc189_0_245>`_ releasing in beta early next year. This setting is enabled by default and may affect server performance. It is recommended to review our `documentation on hardware requirements <https://docs.mattermost.com/install/requirements.html#hardware-requirements>`_ to ensure your servers are appropriately scaled for the size of your user base.
```

2020-11-04 00:23 UTC, esethna approved these changes

2020-11-04 00:30 UTC, merged