v5.30 changelog
mattermost/docs pull request #4114
Opened 2020-11-16 19:02 UTC by amyblais

#### Summary

#### Ticket Link

2020-12-08 13:13 UTC, amyblais commented
@mkraft For v5.30 changelog, please help with the following information:

 - Any new config.json settings
 - Database Changes
 - API Changes
 - Websocket Event Changes

2020-12-08 15:02 UTC, mkraft commented
> @mkraft For v5.30 changelog, please help with the following information:
> 
> * Any new config.json settings
> * Database Changes
> * API Changes
> * Websocket Event Changes

Release notes:

- Db: upgrade db to 5.30 ([#16453](https://github.com/mattermost/mattermost-server/pull/16453), [@cpanato](https://github.com/cpanato))
- Cleanup config store on server initialization errors ([#16440](https://github.com/mattermost/mattermost-server/pull/16440), [@gabrieljackson](https://github.com/gabrieljackson))
- Added support for processing import files through the API. ([#16062](https://github.com/mattermost/mattermost-server/pull/16062), [@streamer45](https://github.com/streamer45))
- In the event a subscription has a payment and there is no card on the account when that payment is processed, an email will be sent to attempt to get the user to pay up. ([#16442](https://github.com/mattermost/mattermost-server/pull/16442), [@nickmisasi](https://github.com/nickmisasi))
- Pre-package and pre-install the channel export plugin for enterprise-ready builds. ([#16406](https://github.com/mattermost/mattermost-server/pull/16406), [@lieut-data](https://github.com/lieut-data))
- Thread related API routes now include 'teamId' path parameter ([#16304](https://github.com/mattermost/mattermost-server/pull/16304), [@reflog](https://github.com/reflog))

2020-12-08 15:08 UTC, mkraft approved these changes

2020-12-09 13:49 UTC, itao requested changes

2020-12-09 13:49 UTC, itao commented on source/administration/changelog.md
> + - Pre-packaged and pre-installed the channel export plugin for enterprise-ready builds.
> Prepackaged and pre-installed the Incident Management as well as Channel Export plugins for enterprise-ready builds.

2020-12-09 14:10 UTC, itao requested changes

2020-12-09 14:10 UTC, itao commented on source/administration/changelog.md
> + - Prepackaged and pre-installed the Incident Management as well as Channel Export plugins for enterprise-ready builds.
Sorry @amyblais it was my mistake, `Pre-packaged` should also have an hyphen. Otherwise LGTM!

2020-12-10 15:03 UTC, itao approved these changes

2020-12-10 15:14 UTC, wiersgallak approved these changes

2020-12-15 17:58 UTC, kongr45gpen commented on source/administration/changelog.md
> + - Added plugin hooks for ``ReationHasBeenAdded`` and ``ReactionHasBeenRemoved``.
```suggestion
 - Added plugin hooks for ``ReactionHasBeenAdded`` and ``ReactionHasBeenRemoved``.
```

(This was a typo in the MR title, see https://github.com/mattermost/mattermost-server/pull/15765/files for the source code)

2020-12-15 23:16 UTC, merged