Added Night Owl Theme
mattermost/docs pull request #4163
Opened 2020-12-09 16:27 UTC by CrHasher

These pull ads a new theme named Night Owl based on the Visual Studio Code theme by Sarah Drasner.

**Note**: The image for the theme is missing from the commit because I would need the address to the Theme Testing server, or someone who can make an image based on this Night Owl theme.

2020-12-09 16:27 UTC, mattermod commented
Hello @CrHasher,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

Per the [Mattermost Contribution Guide](https://developers.mattermost.com/contribute/getting-started/), we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**
Once you have signed the CLA, please comment with `/check-cla` and confirm that the CLA check is green.

This is a standard procedure for many open source projects.

Please let us know if you have any questions.

We are very happy to have you join our growing community! If you're not yet a member, please consider joining our [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets) to meet other contributors and discuss new opportunities with the core team.

2020-12-09 16:31 UTC, CrHasher commented
/check-cla

2020-12-09 20:06 UTC, esethna requested changes
This is an awesome theme!

2020-12-09 20:06 UTC, esethna commented on source/help/settings/theme-colors.rst
> +  {"sidebarBg":"#011627","sidebarText":"#d6deeb","sidebarUnreadText":"#d6deeb","sidebarTextHoverBg":"#1d3b53","sidebarTextActiveBorder":"#ff2c83","sidebarTextActiveColor":"#82aaff","sidebarHeaderBg":
@CrHasher please update mentionBj > mentionBg

cc// @justinegeffen

2020-12-09 20:11 UTC, esethna requested changes

2020-12-09 20:11 UTC, esethna commented on source/help/settings/theme-colors.rst
> +  {"sidebarBg":"#011627","sidebarText":"#d6deeb","sidebarUnreadText":"#d6deeb","sidebarTextHoverBg":"#1d3b53","sidebarTextActiveBorder":"#ff2c83","sidebarTextActiveColor":"#82aaff","sidebarHeaderBg":
@CrHasher what server version were these values generated on? I'm seeing bugs in the theme when I try this myself

![image](https://user-images.githubusercontent.com/14333569/101681824-9bf33c00-3a17-11eb-9e51-525d8666c99b.png)

Can you try on https://community.mattermost.com/ so we are sure the theme works on our newest versions?

2020-12-10 10:15 UTC, CrHasher commented
Just updated the mentions background the rest of the theme is based on the other themes in the themes color page ex. OneDark, Discord and so on. All those themes have duplicate mentionBg fields in the json. Hope that is ok, the theme was tested and works on https://community.mattermost.com/

2020-12-10 10:31 UTC, CrHasher commented
Also note that the #FF2C83 color you see in some places indicates unread and active channels. See this link for details on colors used: https://github.com/VonHeikemen/night-owl-sublime-scheme

2020-12-10 17:47 UTC, esethna commented on source/help/settings/theme-colors.rst
> +.. image:: ../../images/nightOwlDark.PNG
You can add it to the source/images folder on your branch :)

2020-12-10 17:52 UTC, esethna approved these changes

2020-12-15 21:40 UTC, cwarnermm approved these changes
Looks good to me!

2020-12-16 10:18 UTC, merged