Added Bulgarian and Swedish as new languages
mattermost/docs pull request #4212
Opened 2021-01-05 14:53 UTC by ctlaltdieliet

We have 2 new translated languages for Mattermost:
Bulgarian and Swedish. There are added to the documentation.

2021-01-05 14:53 UTC, mattermod commented
Hello @ctlaltdieliet,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2021-01-06 17:45 UTC, justinegeffen commented on source/overview/product.rst
> +- Multiple languages including U.S. English, Chinese (Simplified and Traditional), Bulgarian, Dutch, French, German, Italian, Japanese, Korean, Polish, Brazilian Portuguese, Romanian, Russian, Turkis
```suggestion
- Multiple languages including U.S. English, Chinese (Simplified and Traditional), Bulgarian, Dutch, French, German, Italian, Japanese, Korean, Polish, Brazilian Portuguese, Romanian, Russian, Turkish, Spanish, Swedish, and Ukrainian
```

2021-01-06 17:45 UTC, justinegeffen approved these changes

2021-01-06 17:46 UTC, justinegeffen commented
Thanks so much, @ctlaltdieliet! One minor punctuation edit on my side but otherwise LGTM!

2021-01-07 00:05 UTC, jasonblais approved these changes
Thank you!

2021-01-07 14:58 UTC, jasonblais requested changes
@ctlaltdieliet Here, we can have Bulgarian before Chinese (we list them in alphabetical order in the product overview, after U.S. English).

2021-02-08 13:50 UTC, amyblais commented
Completed via https://github.com/mattermost/docs/pull/4274

2021-02-08 13:50 UTC, closed without merging