Added 2 translated languagues: Bulgarian and Swedish
mattermost/docs pull request #4213
Opened 2021-01-05 15:14 UTC by ctlaltdieliet

2 new translated languages are added to the documentation

2021-01-05 15:14 UTC, mattermod commented
Hello @ctlaltdieliet,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2021-01-07 00:05 UTC, jasonblais approved these changes
Thank you!

2021-01-07 14:57 UTC, jasonblais requested changes
@ctlaltdieliet Actually, can you help update the ordering of the languages to the following?

```
Deutsch - German
English
Español - Spanish
Français - French
Italiano - Italian
Nederlands - Dutch
Polski - Polish
Português (Brasil) - Portuguese
Română - Romanian
Svenska - Swedish
Türkçe - Turkish
Български - Bulgarian
Pусский - Russian
Yкраїнська - Ukrainian
한국어 - Korean
中文 (简体) - Simplified Chinese
中文 (繁體) - Traditional Chinese
日本語 - Japanese
```

This is standard order of languages used by apps like Facebook.

2021-02-08 13:50 UTC, amyblais commented
Completed via https://github.com/mattermost/docs/pull/4274

2021-02-08 13:50 UTC, closed without merging