Update important-upgrade-notes
mattermost/docs pull request #4239
Opened 2021-01-13 23:38 UTC by amyblais

2021-01-14 09:03 UTC, isacikgoz requested changes

2021-01-14 13:20 UTC, isacikgoz approved these changes
LGTM

2021-01-14 14:10 UTC, cwarnermm reviewed
Suggested update provided inline.

2021-01-14 14:26 UTC, cwarnermm approved these changes
Looks great!

2021-01-14 16:19 UTC, amyblais commented on source/administration/important-upgrade-notes.rst
> +   TLS versions 1.0 and 1.1 have been deprecated by browser vendors. In Mattermost Server v5.32 (February 16), mmctl will return an error when connected to Mattermost servers deployed with these TLS
Also added a date for the TLS deprecation

2021-01-15 11:40 UTC, merged

2021-01-15 18:56 UTC, wiersgallak commented on source/administration/important-upgrade-notes.rst
> +   Customers using the ``mattermost`` binary with the “--platform” flag, or using the ``platform`` binary directly, to run the Mattermost server application via a systemd file or custom script will b
Recommended edits: 

The ``platform`` binary and “--platform” flag will be deprecated in a future release. If you are using the “--platform” flag or using the ``platform`` binary directly to run the Mattermost server application via a systemd file or custom script, you will be required to use only the ``mattermost`` binary.