Changelog notes for v5.30 / v5.29 backports
mattermost/docs pull request #4244
Opened 2021-01-15 17:52 UTC by amyblais

for https://mattermost.atlassian.net/browse/MM-31973

2021-01-15 18:00 UTC, esethna requested changes

2021-01-15 18:00 UTC, esethna commented on source/administration/changelog.md
> +  - Fixed an issue where a column in the ``ThreadMemberships`` table was missing. Admins planning to enable [Collapsed Reply Threads](https://mattermost.com/blog/dev-sneak-peek-collapsed-reply-thread
Fixed an issue where the ``UnreadMentions`` column was missing in the ``ThreadMemberships`` for servers upgrading from an earlier version. Admins planning to enable [Collapsed Reply Threads](https://mattermost.com/blog/dev-sneak-peek-collapsed-reply-threads/) (available in beta in Q1 2021) are recommended to upgrade to v5.30.2 or later.

2021-01-18 10:10 UTC, reflog approved these changes

2021-01-18 18:57 UTC, esethna requested changes

2021-01-18 18:57 UTC, esethna commented on source/administration/changelog.md
> + - Fixed an issue where the ``UnreadMentions`` column was missing in the ``ThreadMemberships`` table for servers upgrading from an earlier version. Admins planning to enable [Collapsed Reply Threads]
...was missing in the ``ThreadMemberships`` table for servers upgrading from Mattermost Server v5.29.0

2021-01-18 18:57 UTC, esethna commented on source/administration/changelog.md
> +  - Fixed an issue where the ``UnreadMentions`` column was missing in the ``ThreadMemberships`` table for servers upgrading from an earlier version. Admins planning to enable [Collapsed Reply Threads
...was missing in the ``ThreadMemberships`` table for servers upgrading from v5.29.0

2021-01-18 18:57 UTC, esethna commented on source/administration/changelog.md
> +  - Fixed an issue where the ``UnreadMentions`` column was missing in the ``ThreadMemberships`` table for servers upgrading from an earlier version. Admins planning to enable [Collapsed Reply Threads
...was missing in the ``ThreadMemberships`` table for servers upgrading from v5.29.0

2021-01-18 18:57 UTC, esethna commented
@amyblais see the suggestions above since the issue is less severe than originally thought (it only affects servers upgrading from exactly v5.29.0)

2021-01-18 19:03 UTC, esethna approved these changes

2021-01-18 19:08 UTC, merged