Update important-upgrade-notes.rst
mattermost/docs pull request #4272
Opened 2021-01-28 15:48 UTC by amyblais

Also to send to GitLab.

2021-01-28 16:55 UTC, amyblais commented
Add: config changes re channel sidebar: https://github.com/mattermost/docs/pull/4266/files

2021-01-28 16:57 UTC, amyblais commented
@agnivade Is the go update to 1.15.5 something that should also be documented here? (It's already in the changelog)

2021-01-28 18:14 UTC, agnivade commented
IMO having it in release notes should be sufficient.

2021-01-29 13:52 UTC, streamer45 commented on source/administration/important-upgrade-notes.rst
> +|                                                    | changing the number of parameters or their type) will fail to compile/execute as soon as its dependencies get updated.
I'd change this section to:

```
Breaking changes to the Golang client API were introduced:
GetPostThread, GetPostsForChannel, GetPostsSince, GetPostsAfter, GetPostsBefore, GetPostsAroundLastUnread now require an additional collapsedThreads parameter to be passed. 
Any client making use of these functions will need to update them when upgrading its dependencies.
```

2021-01-29 14:03 UTC, streamer45 approved these changes
Looks good :+1:

2021-02-03 01:54 UTC, esethna requested changes

2021-02-03 01:54 UTC, esethna commented on source/administration/important-upgrade-notes.rst
> +|                                                    | functional if the Legacy Sidebar (``EnableLegacySidebar``) is enabled since they are not compatible with the new sidebar experience.
@amyblais please add a link embeded somewhere in here to the blog that will be published on the new sidebar: https://mattermost.com/blog/custom-collapsible-channel-categories/

2021-02-04 14:14 UTC, wiersgallak approved these changes
LGTM

2021-02-04 18:53 UTC, merged