[MM-32393] Add documentation for the custom nginx template
mattermost/docs pull request #4295
Opened 2021-02-08 11:16 UTC by mgdelacroix

#### Summary
Adds documentation for the custom `nginx` template for Omnibus.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-32393

2021-02-08 11:18 UTC, grundleborg approved these changes

2021-02-10 20:57 UTC, justinegeffen requested changes
Thanks Miguel! This is awesome. I've made some suggestions around wording - let me know if the context has changed at all or if the suggestions don't work. :)

2021-02-10 20:57 UTC, justinegeffen commented on source/install/mattermost-omnibus.rst
> +- ``nginx_template``: Optional path to a custom nginx template.
```suggestion
- ``nginx_template``: Optional path to a custom NGINX template.
```

2021-02-10 20:57 UTC, justinegeffen commented on source/install/mattermost-omnibus.rst
> +Using a custom nginx template
```suggestion
Using a custom NGINX template
```

2021-02-10 20:57 UTC, justinegeffen commented on source/install/mattermost-omnibus.rst
> +Mattermost Omnibus generates a ``nginx`` configuration depending on how the different properties of the ``mmomni.yml`` file are set, but it is possible that you need to customize the configuration fu
```suggestion
Mattermost Omnibus generates an ``nginx`` configuration depending on how the different properties of the ``mmomni.yml`` file are set. However, you may need to customize the configuration further to support other use cases, such as using custom SSL certificates. For those cases, Omnibus supports using a custom ``nginx`` template to generate its configuration. 

To use this feature, you need to copy and modify the original template located at ``/opt/mattermost/mmomni/ansible/playbooks/mattermost.conf`` to a new location. Then, you can either use the variables and internal logic already bundled in the template and modify the parts that you need, or use a fully static configuration instead.
```

2021-02-10 20:57 UTC, justinegeffen commented on source/install/mattermost-omnibus.rst
> +After the template has been customized, you need to add a ``nginx_template`` property to the ``/etc/mattermost/mmomni.yml`` configuration file, and then run ``mmomni reconfigure``. The reconfigure pr
```suggestion
After the template has been customized, add an ``nginx_template`` property to the ``/etc/mattermost/mmomni.yml`` configuration file, and then run ``mmomni reconfigure``. The reconfigure process will use the new template to generate the NGINX final configuration. You can check the contents of the ``/etc/nginx/conf.d/mattermost.conf`` file to validate that the changes were applied successfully.
```

2021-02-10 20:57 UTC, justinegeffen commented on source/install/mattermost-omnibus.rst
> +This feature is available since Mattermost Omnibus version 5.32.0.
```suggestion
This feature is available from Mattermost Omnibus version 5.32.0.
```

2021-02-10 20:57 UTC, justinegeffen commented on source/install/mattermost-omnibus.rst
> +Please be careful when using this feature, as making changes to the custom template can cause the reconfigure process to fail, or the generated nginx configuration to be invalid.
```suggestion
Please be careful when using this feature, as making changes to the custom template can cause the reconfigure process to fail, or the generated NGINX configuration to be invalid.
```

2021-02-15 11:30 UTC, justinegeffen approved these changes

2021-02-15 18:19 UTC, merged