Verify SAML setup documentation for NameID
mattermost/docs pull request #4296
Opened 2021-02-08 15:39 UTC by cwarnermm

Documentation for: https://github.com/mattermost/docs/issues/4267

Updated:
- Self Managed Admin Guide > Onboard Users > SAML Single Sign-On (E20) > Configure SAML with Microsoft ADFS for Windows Server 2012 > Create Claim Rules
   - Updated step 3 to add another bullet point for creating a claim rule for `NameID`

2021-02-08 16:54 UTC, justinegeffen reviewed
I changed the formatting of the attribute names to match the formatting in the list - italics seemed out of place. The other option is to make the format bold to match UI formatting convention.

2021-02-08 16:54 UTC, justinegeffen commented on source/deployment/sso-saml-adfs-msws2016.rst
> +From Mattermost 3.4, the *FirstName* and *LastName* attributes are optional.
```suggestion
From Mattermost version 3.4, the ``FirstName`` and ``LastName`` attributes are optional.
```

2021-02-08 16:54 UTC, justinegeffen commented on source/deployment/sso-saml-adfs.rst
> +From Mattermost 3.4, the *FirstName* and *LastName* attributes are optional.
```suggestion
From Mattermost version 3.4, the ``FirstName`` and ``LastName`` attributes are optional.
```

2021-02-09 20:43 UTC, sbishel requested changes

2021-02-09 20:43 UTC, sbishel commented on source/deployment/sso-saml-adfs-msws2016.rst
> +  - From the **LDAP Attribute column**, select ``E-Mail-Addresses``. From the **Outgoing Claim Type**, type ``NameID``.
```suggestion
  - From the **LDAP Attribute column**, select ``E-Mail-Addresses``. From the **Outgoing Claim Type**, type ``Name ID``.
```

2021-02-09 20:43 UTC, sbishel commented on source/deployment/sso-saml-adfs.rst
> +  - From the **LDAP Attribute column**, select ``E-Mail-Addresses``. From the **Outgoing Claim Type**, type ``NameID``.
```suggestion
  - From the **LDAP Attribute column**, select ``E-Mail-Addresses``. From the **Outgoing Claim Type**, type ``Name ID``.
```

2021-02-09 20:46 UTC, sbishel approved these changes

2021-02-10 20:39 UTC, justinegeffen approved these changes

2021-02-17 13:03 UTC, merged