MM-32227 - Update docs for saved messages
mattermost/docs pull request #4298
Opened 2021-02-08 16:46 UTC by cwarnermm

Docs ticket: https://mattermost.atlassian.net/browse/MM-32227

Updated:
- Users Guide > Messaging > Flagging Messages
   - Updated all references of "flagging messages" to "saving messages"

Note: Changing the source file will be tracked via https://mattermost.atlassian.net/browse/MM-32672

2021-02-08 19:15 UTC, cwarnermm commented
Note: 1 product documentation page remains as-is for now: https://docs.mattermost.com/deployment/bulk-loading-data-format.html (which matches API product docs: https://api.mattermost.com/#tag/posts/paths/~1users~1{user_id}~1posts~1flagged/get)

2021-02-08 19:25 UTC, esethna approved these changes

2021-02-10 20:38 UTC, justinegeffen requested changes

2021-02-10 20:38 UTC, justinegeffen commented on source/administration/telemetry.rst
> +  - *Advanced Feature Discovery Diagnostics:* Reacted to a message; favorited or un-favorited a channel; saved or un-saved a message; pinned or un-pinned a message; replied to a message; expanded the
```suggestion
  - *Advanced Feature Discovery Diagnostics:* Reacted to a message; favorited or unfavorited a channel; saved or unsaved a message; pinned or unpinned a message; replied to a message; expanded the right-hand sidebar; started or finished a WebRTC video call (only in v5.5 and earlier); created or deleted a personal access token; added or removed post:all or post:channels permission; created a category in the sidebar
```

2021-02-10 20:38 UTC, justinegeffen commented on source/help/getting-started/creating-teams.rst
> +* We don’t yet support search or channels across teams, which can impact the cross-team user experience. This includes general searches, saved posts and recent mentions.
```suggestion
* We don’t yet support search or channels across teams, which can impact the cross-team user experience. This includes general searches, saved posts, and recent mentions.
```

2021-02-10 20:38 UTC, justinegeffen commented on source/help/getting-started/messaging-basics.rst
> +**Save messages for follow up** by clicking the **Save** icon next to the
```suggestion
**Save messages for follow up** using the **Save** icon next to the
```

2021-02-10 20:38 UTC, justinegeffen commented on source/help/messaging/flagging-messages.rst
> +Saving a message helps you mark messages for follow up. Your saved messages are personal, and cannot be seen by other users. There is no limit to the number of posts you can save.
```suggestion
Saving a message helps you mark messages for follow up. Your saved messages are personal, and can't be seen by other users. There's no limit to the number of posts you can save.
```

2021-02-10 20:38 UTC, justinegeffen commented on source/help/messaging/flagging-messages.rst
> +One way we like to use saved messages is to mark messages we want to respond to later. It's useful when someone asks for something that requires work. We save the post, keep doing what we're doing, a
```suggestion
One way to use saved messages is to mark messages you want to respond to later. You can save the post in the list of **Saved Posts**, refer back to it when you're able to, and once complete you can remove it from the list.
```

2021-02-10 20:38 UTC, justinegeffen commented on source/help/messaging/flagging-messages.rst
> +=======================
```suggestion
=====================
```

2021-02-10 20:38 UTC, justinegeffen commented on source/help/messaging/flagging-messages.rst
> +To view a list of your **Saved Posts**, click the **Save** icon at the top of the channel.
```suggestion
To view a list of your **Saved Posts**, select the **Save** icon at the top of the channel.
```

2021-02-10 20:38 UTC, justinegeffen commented on source/help/messaging/flagging-messages.rst
> +To remove an item from the **Saved Posts** list, click the **Save** icon beside a message to clear it.
```suggestion
To remove an item from the **Saved Posts** list, select the **Save** icon next to message to clear it.
```

2021-02-10 20:39 UTC, justinegeffen commented
There's a section that I reworded because it's very different to our usual style of writing - I may have read it out of context though, so happy to bounce that around. 

Otherwise just some minor suggestions. :)

2021-02-10 20:41 UTC, cwarnermm commented
@justinegeffen - You're right about that one section reading quite differently. I agree with all of your updates, and thank you for finding additional pre-existing "clicks" that I missed in the first round! :)

2021-02-10 21:17 UTC, justinegeffen approved these changes

2021-02-10 21:17 UTC, merged