GDPR FAQ Update
mattermost/docs pull request #4348
Opened 2021-02-24 22:11 UTC by cwarnermm

Documentation task: https://mattermost.atlassian.net/browse/MM-33042

Updated:
- Overview > Certifications and Compliance Overview > GDPR Compliance > FAQ
   - Added new FAQ topic to answer the question "How do you ensure that personal data stays within the European Union?

2021-02-25 03:44 UTC, wiersgallak requested changes

2021-02-25 03:44 UTC, wiersgallak commented on source/overview/compliance.rst
> +When the customer’s installation of Mattermost is self-hosted, Mattermost will not be processing any personal data under the jurisdiction of the data privacy laws governing within the European Union.
```suggestion
When the customer’s installation of Mattermost is self-hosted, Mattermost does not process any personal data under the jurisdiction of the data privacy laws governing within the European Union. The Mattermost support team leverages Zendesk customer service software, which hosts Mattermost information within the United States. For more information on Zendesk, please see their `Privacy and Data Protection <https://www.zendesk.com/company/privacy-and-data-protection/#gdpr-sub>`__ page.
```

2021-03-03 02:58 UTC, adamjclarkson approved these changes

2021-03-03 17:14 UTC, cwarnermm commented
@wiersgallak - Are there additional reviews we'd like this change to go through prior to publication?

2021-03-03 17:18 UTC, wiersgallak reviewed
This information came from Jamie if I recall, so I think we are good from that perspective. Wondering if we should refer them back to the Privacy Policy as well in the statement.

2021-03-03 18:21 UTC, cwarnermm commented
Thanks, @wiersgallak! I've added a link to our Privacy Policy to the new FAQ topic.

2021-03-03 20:23 UTC, wiersgallak approved these changes
Thanks!

2021-03-04 19:32 UTC, justinegeffen commented on source/overview/compliance.rst
> +However, pursuant to Section (b) of Article 49 of GDPR, transfers of personal data which are "necessary for the performance of a contract between the data subject and the controller" may be transferr
```suggestion
However, pursuant to Section (b) of Article 49 of GDPR, transfers of personal data which are "necessary for the performance of a contract between the data subject and the controller" may be transferred to a third country or international organization. Accordingly these transfers would be done in alignment with the requirements of GDPR. For more information, see our `Mattermost Privacy Policy <https://mattermost.com/privacy-policy/>`__ page.

```

2021-03-04 19:32 UTC, justinegeffen approved these changes

2021-03-04 19:37 UTC, merged