Modified postgres folder path for clarity
mattermost/docs pull request #4374
Opened 2021-03-09 14:32 UTC by coltoneshaw

#### Summary
We specify an absolute path of `/etc/postgresql/10/main` when Ubuntu 20.04 installs version 12. Replaced the path and added a small amount of instructions to make this more clear.

2021-03-09 15:21 UTC, cwarnermm requested changes
Thank you for adding clarity to the product documentation. This update affects an additional installation page for Ubuntu 18.04.

2021-03-09 15:21 UTC, cwarnermm commented on source/install/install-ubuntu-2004-postgresql.rst
> +9. (Optional) If you use a different server for your database and the Mattermost server, you may allow PostgreSQL to listen on all assigned IP addresses. To do so, open ``/etc/postgresql/{version}/ma
```suggestion
9. (Optional) If you use a different server for your database and the Mattermost server, you may allow PostgreSQL to listen on all assigned IP addresses. To do so, open ``/etc/postgresql/{version}/main/postgresql.conf`` in a text editor as *root* user. Replace `{version}` with the version of PostgreSQL that is currently running. As a best practice, ensure that only the Mattermost server is able to connect to the PostgreSQL port using a firewall.
```

2021-03-09 15:21 UTC, cwarnermm commented on source/install/install-ubuntu-2004-postgresql.rst
> +9. (Optional) If you use a different server for your database and the Mattermost server, you may allow PostgreSQL to listen on all assigned IP addresses. To do so, open ``/etc/postgresql/{version}/ma
Thank you! We use the same hard-coded convention for the Ubuntu 18.04 installation documentation as well (https://docs.mattermost.com/install/install-ubuntu-1804.html#) Could you make the same change there for consistency, please?

2021-03-26 14:23 UTC, cwarnermm commented
@justinegeffen - Would you be able to make this change to a second file as well, please? This change would be beneficial on the installation page for Ubuntu 18.04.

2021-03-29 06:48 UTC, justinegeffen commented on source/install/install-ubuntu-2004-postgresql.rst
> +9. (Optional) If you use a different server for your database and the Mattermost server, you may allow PostgreSQL to listen on all assigned IP addresses. To do so, open ``/etc/postgresql/{version}/ma
```suggestion
9. (Optional) If you use a different server for your database and the Mattermost server, you may allow PostgreSQL to listen on all assigned IP addresses. To do so, open ``/etc/postgresql/{version}/main/postgresql.conf`` in a text editor as *root* user. Replace ``{version}`` with the version of PostgreSQL that's currently running. As a best practice, ensure that only the Mattermost server is able to connect to the PostgreSQL port using a firewall.
```

2021-03-29 06:48 UTC, justinegeffen commented on source/install/install-ubuntu-2004-postgresql.rst
>    **If the Mattermost server and the database are on the same machine**:
```suggestion
  **If the Mattermost server and the database are on the same machine:**
```

2021-03-29 06:54 UTC, justinegeffen commented
> @justinegeffen - Would you be able to make this change to a second file as well, please? This change would be beneficial on the installation page for Ubuntu 18.04.
Done. :)

2021-03-29 12:28 UTC, cwarnermm approved these changes
Thank you so much for applying these changes!

2021-04-09 17:10 UTC, merged

2021-04-09 17:42 UTC, amyblais commented on source/install/install-ubuntu-1804-postgresql.rst
> +.. note::
@justinegeffen The last "note" section (same for the second file) is not properly formatted (minor issue).