fix and update the silent deployment script for the Windows app
mattermost/docs pull request #4394
Opened 2021-03-17 15:15 UTC by flexo3001

#### Summary
This fixes a timing problem with the silent install batch script and updates it the config.json to a recent version.

2021-03-18 14:16 UTC, Willyfrog requested changes
Thank you for taking the time to improve our docs.

I like a lot of the changes you made, which make sense for this script. Can you also verify that the values prosed match the [default ones in the docs](https://docs.mattermost.com/help/apps/desktop-guide.html#app-options)? I can see that minimize to tray should be false

2021-03-25 16:41 UTC, flexo3001 commented
> Thank you for taking the time to improve our docs.
> 
> I like a lot of the changes you made, which make sense for this script. Can you also verify that the values prosed match the [default ones in the docs](https://docs.mattermost.com/help/apps/desktop-guide.html#app-options)? I can see that minimize to tray should be false

I copied it from the config.json generated at the first opening of the desktop app. We can change the defaults in the docs too or change them in the desktop app i guess.

![Screen Shot 2021-03-25 at 17 39 21](https://user-images.githubusercontent.com/1415596/112509845-27a79300-8d91-11eb-938e-d3a8eafccb45.png)

2021-03-26 11:47 UTC, Willyfrog commented
my bad, the documentation is outdated, I just reviewed and your changes reflect the latest changes in code which were in fact modified to a new default.

thanks!

2021-03-26 11:47 UTC, Willyfrog approved these changes

2021-03-26 12:01 UTC, justinegeffen approved these changes

2021-03-26 12:01 UTC, merged