MM-31674 Cloud app/product notices for ext dependecies
mattermost/docs pull request #4418
Opened 2021-03-25 21:07 UTC by cwarnermm

Documentation for: mattermost/mattermost-server#16871

Updated:
- Cloud Admin Guide > Configuration > Site Configuration > In-Product Notices > Administrator Notices
   - Updated description to include deprecation of external dependencies

2021-03-25 21:10 UTC, cwarnermm commented
@wiersgallak - Please confirm that Admin Notices will inform Cloud System Admins of the following:
- when a new server version is available
- when external dependencies are being deprecated
- when a server upgrade is recommended due to ending support life cycles
- when recommended server configuration options can optimize the user experience of their deployment

I suspect that not all of these are true for Cloud System Admins; I can update the product documentation accordingly.

2021-03-25 21:51 UTC, justinegeffen approved these changes

2021-03-26 21:03 UTC, wiersgallak commented
@cwarnermm We will not use in-product notices for Cloud for these use cases as they are on-premise only: 
- when a new server version is available
- when external dependencies are being deprecated
- when a server upgrade is recommended due to ending support life cycles

This one may still be applicable as long as the configuration option is available in the System Console for Cloud instances: 
- when recommended server configuration options can optimize the user experience of their deployment

2021-03-30 14:51 UTC, wiersgallak requested changes
Cloud will not have external dependencies or life cycles that admins need to worry about.  We manage all of that for them.

2021-03-30 14:51 UTC, wiersgallak commented on source/cloud/cloud-administration/site-configuration.rst
> +Administrator notices inform System Admins when a new server version is available, when external dependencies are being deprecated, or when a server upgrade is recommended due to ending support life
```suggestion
System Admins may receive notices about recommended configuration options to optimize the user experience of their workspace.
```

```

2021-03-31 13:49 UTC, cwarnermm commented
Thanks, @wiersgallak!

2021-04-06 14:58 UTC, wiersgallak approved these changes

2021-04-07 18:44 UTC, merged