MM-31717: Remove HTTP clustering
mattermost/docs pull request #4545
Opened 2021-05-04 18:41 UTC by cwarnermm

Documentation for: https://github.com/mattermost/mattermost-server/pull/17409

Updated:
- Self-Managed Admin Guide > Configure Mattermost > Configuration Settings > Environment > High Availability
   - Updated the Use Gossip configuration setting with a note indicating that Gossip clustering can no longer be disabled from Mattermost Server, and that all cluster traffic uses the gossip protocol.

2021-05-04 19:04 UTC, justinegeffen reviewed
I added two rewording suggestions. My third suggestion seemed like it may work but may also be missing context!

2021-05-04 19:04 UTC, justinegeffen commented on source/administration/config-settings.rst
> +   Gossip clustering can no longer be disabled from Mattermost Server v5.35. All cluster traffic uses the gossip protocol.
```suggestion
   All cluster traffic uses the gossip protocol. From Mattermost Server v5.35 gossip clustering can no longer be disabled.
```

2021-05-04 19:04 UTC, justinegeffen commented on source/deployment/cluster.rst
> +From Mattermost Server v5.35, `gossip clustering can no longer be disabled <https://docs.mattermost.com/administration/config-settings.html#use-gossip>`__. All cluster traffic uses the gossip protoco
```suggestion
All cluster traffic uses the gossip protocol. From Mattermost Server v5.35, `gossip clustering can no longer be disabled <https://docs.mattermost.com/administration/config-settings.html#use-gossip>`__.
```

2021-05-04 19:04 UTC, justinegeffen commented on source/deployment/cluster.rst
> +When upgrading a High Availability cluster, you can't upgrade other nodes in the cluster when one node isn't using the gossip protocol. You must use gossip to complete a High Availability upgrade, or
```suggestion
When upgrading a High Availability cluster, you can't upgrade other nodes in the cluster when one node isn't using the gossip protocol. You must use gossip to complete a High Availability upgrade. Alternatively you can shut down all nodes and bring them all up individually following an upgrade.
```

2021-05-04 19:05 UTC, cwarnermm commented
Great updates, @justinegeffen -- Thank you!

2021-05-04 19:07 UTC, justinegeffen approved these changes

2021-05-05 03:26 UTC, agnivade requested changes
From @amyblais's comment [here](https://github.com/mattermost/mattermost-server/pull/17409#issuecomment-820370093), I was of the understanding that this is coming in 5.36, not 5.35. Can you please double-check? Thanks.

2021-05-05 12:54 UTC, cwarnermm commented
Thanks so much @agnivade! You're absolutely right - this is a v5.36 update. I'll update the version references in the docs.

2021-05-05 12:57 UTC, cwarnermm commented on source/administration/config-settings.rst
> +   All cluster traffic uses the gossip protocol. From Mattermost Server v5.35 gossip clustering can no longer be disabled.
```suggestion
   All cluster traffic uses the gossip protocol. From Mattermost Server v5.36 gossip clustering can no longer be disabled.
```

2021-05-05 12:57 UTC, cwarnermm commented on source/deployment/cluster.rst
> +All cluster traffic uses the gossip protocol. From Mattermost Server v5.35, `gossip clustering can no longer be disabled <https://docs.mattermost.com/administration/config-settings.html#use-gossip>`_
```suggestion
All cluster traffic uses the gossip protocol. From Mattermost Server v5.36, `gossip clustering can no longer be disabled <https://docs.mattermost.com/administration/config-settings.html#use-gossip>`__.
```

2021-05-05 13:32 UTC, wiersgallak approved these changes

2021-05-05 13:51 UTC, agnivade approved these changes

2021-06-15 16:39 UTC, merged