MM-34893 Completely disabled Admin Advisor
mattermost/docs pull request #4547
Opened 2021-05-04 19:17 UTC by cwarnermm

Documentation for: https://github.com/mattermost/mattermost-server/pull/17422

Updated:
- Self-Managed Admin Guide > Administration > In-Product Notices > Admin Advisor notices
   - Added note indicating that Admin Advisor notices are disabled as of v5.35 and later

2021-05-04 19:37 UTC, cwarnermm commented
@jasonblais There is one more small related update that @harshilsharma63 is going to make for this via https://github.com/mattermost/docs/pull/4503

2021-05-04 20:16 UTC, justinegeffen commented on source/administration/notices.rst
> +.. note::
This may work better swapped around (i.e., the note beneath the "Admin Advisor notices..." sentence? Other than that, LGTM. :)

2021-05-04 20:16 UTC, justinegeffen approved these changes

2021-05-04 21:01 UTC, jasonblais requested changes

2021-05-05 12:47 UTC, jasonblais approved these changes

2021-05-13 17:30 UTC, merged