Update important-upgrade-notes.rst
mattermost/docs pull request #4551
Opened 2021-05-05 17:36 UTC by amyblais

2021-05-05 17:40 UTC, esethna requested changes

2021-05-05 17:40 UTC, esethna commented on source/administration/important-upgrade-notes.rst
> +| v5.35.0                                            | v5.35.0 introduces a new feature to search for files. Search results for files shared in the past may be incomplete until a
v5.35.0 introduces a new feature to search for files. Search results for files shared in the past may be incomplete until a content extraction command is executed to extract and index the content of files already in the database. Instances running Elasticsearch or Bleve search backends will also need to execute a Bulk Indexing after the content extraction is complete. Please see more details in this blog post.

2021-05-05 17:47 UTC, esethna approved these changes
Thanks!

2021-05-05 18:08 UTC, cwarnermm reviewed
Suggestions provided inline. The key feedback is that the new file search feature specifically searches on file contents, not the files themselves.

2021-05-05 18:08 UTC, cwarnermm commented on source/administration/important-upgrade-notes.rst
> +| v5.35.0                                            | v5.35.0 introduces a new feature to search for files. Search results for files shared in the past may be incomplete until a
```suggestion
| v5.35.0                                            | v5.35.0 introduces a new feature to search for the contents of files shared in Mattermost. Search results for file contents shared prior to upgrading to v5.35.0 may be incomplete until a                                      |
```

2021-05-05 18:10 UTC, amyblais commented on source/administration/important-upgrade-notes.rst
> +| v5.35.0                                            | v5.35.0 introduces a new feature to search for files. Search results for files shared in the past may be incomplete until a
@esethna Please help confirm ^

2021-05-07 00:18 UTC, esethna approved these changes

2021-05-07 12:30 UTC, merged