Update Windows Requirement
mattermost/docs pull request #4588
Opened 2021-05-18 00:50 UTC by ahmaddanialmohd

#### Summary
Remove Windows 7+ from **line 32** since it has already reached its EOL.

2021-05-19 15:21 UTC, amyblais requested changes
Does this need to be announced to customers?

2021-05-19 15:28 UTC, cwarnermm commented
I imagine that there are additional references to Windows 7 that should also be removed for consistency. I've logged https://mattermost.atlassian.net/browse/MM-35873 for this effort.

2021-05-19 16:19 UTC, cwarnermm commented on source/install/requirements.rst
> +    "Windows", "Windows 8.1, and 10"
```suggestion
    "Windows", "Windows 8.1 and 10"
```

2021-05-19 16:20 UTC, cwarnermm approved these changes
Approved with the change proposed inline

2021-05-19 21:56 UTC, esethna approved these changes

2021-06-03 19:38 UTC, cwarnermm commented
@esethna - See Amy's question above about whether or not we should announce that we've formally dropped support for Windows 7.

2021-06-03 20:55 UTC, esethna commented
@amyblais @cwarnermm yes we should probably do some communication around this. @amyblais I'll leave this in your court to figure out. 0/5, but perhaps we do this with the v6.0 launch among other deprecations/depreciations to make the communication easier. 

Some resources that may help with the communication: https://support.microsoft.com/en-us/windows/windows-7-support-ended-on-january-14-2020-b75d4580-2cc7-895a-2c9c-1466d9a53962

2021-10-04 15:45 UTC, cwarnermm commented
@amyblais - Is additional work remaining on this ticket?

2021-10-04 16:08 UTC, amyblais commented
@cwarnermm No, this can be merged with v6.0 docs, or a new PR can be submitted since this has conflicts.

2021-10-04 16:16 UTC, cwarnermm commented
Thanks, @amyblais. I agree that trying to manage the conflicts in this PR will take far more time than applying this update in the ``v6.0-documentation`` branch. I'll get this update in today.

2021-10-04 17:28 UTC, cwarnermm commented
Closing this ticket since the changes required have been applied via https://github.com/mattermost/docs/pull/5110 for v6.0.

2021-10-04 17:28 UTC, closed without merging