Add sendmail SMTP configuration option
mattermost/docs pull request #4682
Opened 2021-06-29 07:27 UTC by bbodenmiller

#### Summary

#### Ticket Link

2021-06-29 07:27 UTC, mattermod commented
Hello @bbodenmiller,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2021-06-29 19:28 UTC, cwarnermm commented
@coltoneshaw - Are you open to reviewing this documentation PR for technical accuracy?

2021-06-29 20:20 UTC, coltoneshaw requested changes
I think we can most likely move this up to be a suggestion under the above bullet, like below. Since that above bullet technically includes it. However, technically there are no issues with using localhost and port 25.

```
If you don't have an SMTP service, here are simple instructions:
- Amazon Simple Email Service (SES):
- Local ``sendmail`` can be used by using **Server Name** ``127.0.0.1``
```

2021-06-30 13:47 UTC, cwarnermm commented
Thanks, @coltoneshaw. Great feedback! I agree with incorporating this new content into the bullet point that reads "If you don't have an SMTP service, here are simple instructions..."

@bbodenmiller - Are you open to updating your PR with this feedback? If you'd prefer, I'm can help complete this update.

2021-07-01 06:18 UTC, bbodenmiller commented
Might get done faster if you make the tweak.

On Wed, Jun 30, 2021, 6:47 AM Carrie Warner (Mattermost) <
***@***.***> wrote:

> Thanks, @coltoneshaw <https://github.com/coltoneshaw>. Great feedback! I
> agree with incorporating this new content into the bullet point that reads
> "If you don't have an SMTP service, here are simple instructions..."
>
> @bbodenmiller <https://github.com/bbodenmiller> - Are you open to
> updating your PR with this feedback? If you'd prefer, I'm can help complete
> this update.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/mattermost/docs/pull/4682#issuecomment-871419693>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAJDGTDD4IRKQJ3T4WSPWDTTVMN7BANCNFSM47PPX6YA>
> .
>

2021-07-01 15:13 UTC, coltoneshaw approved these changes

2021-07-01 15:14 UTC, coltoneshaw commented
@cwarnermm / @bbodenmiller - I adjusted the requested structure. Let me know if it flows okay.

2021-07-03 11:59 UTC, bbodenmiller commented on source/install/smtp-email-setup.rst
> +        - By local ``sendmail`` can be used by using **Server Name** ``127.0.0.1`` with **Port** ``25``
@coltoneshaw `by` seems a bit weird here.

2021-07-06 12:35 UTC, cwarnermm approved these changes
This is a great documentation update - thank you so much!

2021-07-06 12:35 UTC, cwarnermm commented on source/install/smtp-email-setup.rst
> +        - By local ``sendmail`` can be used by using **Server Name** ``127.0.0.1`` with **Port** ``25``
Agreed. Looks like "by" isn't needed.

2021-07-09 20:22 UTC, merged