Troubleshooting for NGINX error log: Connection Refused
mattermost/docs pull request #4930
Opened 2021-08-05 15:34 UTC by cwarnermm

Documentation ticket: https://mattermost.atlassian.net/browse/MM-37000

Updated:
- Updated shared installation topic Configuring NGINX with SSL and HTTP-2 to clarify that examples in the docs may not match network configuration, and to recommend using IP address over ``localhost`` in situations where the local machine resolves ``localhost`` to more than one IP address

2021-08-05 19:48 UTC, justinegeffen reviewed
One rewording (which may or may not work, I can't decide) and one typo - otherwise looks good to me!

2021-08-05 19:48 UTC, justinegeffen commented on source/install/config-proxy-nginx.rst
> +  - Examples in this documentation are using a private IP address, which may not match your network configuration.
```suggestion
  - Note that the IP address included in the examples in this documentation may not match your network configuration.
```

2021-08-05 19:48 UTC, justinegeffen commented on source/install/config-proxy-nginx.rst
> +Why does NGINX fail when installing Gitlab CE with Mattermost on Azure?
```suggestion
Why does NGINX fail when installing GitLab CE with Mattermost on Azure?
```

2021-08-05 19:48 UTC, justinegeffen approved these changes

2021-08-05 19:52 UTC, cwarnermm commented on source/install/config-ssl-http2-nginx.rst
> +   - Examples in this documentation are using a private IP address, which may not match your network configuration.
```suggestion
   - Note that the IP address included in the examples in this documentation may not match your network configuration. 
```

2021-08-05 19:55 UTC, coltoneshaw requested changes
It looks good and works fine! My only thought is should we be slightly more explicit on when you'd use it? Ex:

"If you're running NGINX on the same machine as mattermost and it resolves ``localhost``"

2021-08-06 14:33 UTC, cwarnermm commented
@coltoneshaw - Thank you so much! This additional context is a great addition!

2021-08-06 14:34 UTC, coltoneshaw approved these changes

2021-08-06 14:44 UTC, merged