Formatting fix to return content
mattermost/docs pull request #4936
Opened 2021-08-06 15:46 UTC by cwarnermm

Formatting was preventing docs content from displaying on the page. Thanks @PeterDaveHello for letting us know about this issue!

2021-08-06 15:59 UTC, PeterDaveHello requested changes
It's more than just a few lines, please take a look at https://github.com/mattermost/docs/pull/4924/files?short_path=fcc1287#diff-fcc12871eb71ce483f8dbcabf9b5a0a79ae12f56e7b91a91b6fd3fba83b1a3bd

2021-08-06 21:09 UTC, cwarnermm commented
Thank you so much, @PeterDaveHello. You're absolutely right that more than the one section was affected in error. I believe I've restored all of the code samples to the page. Please let me know if anything else looks out of place.

2021-08-09 10:37 UTC, PeterDaveHello commented
Cool, thanks, sorry that I can't personally check every line of it right now, please feel free to land it if it looks good enough to you :D

2021-08-09 17:06 UTC, justinegeffen approved these changes

2021-08-09 17:12 UTC, merged