Update configuration-settings.rst
mattermost/docs pull request #5270
Opened 2021-11-17 19:48 UTC by wiersgallak

Clarified the requirement of email verification configuration must be set for restrictions to be applied.

#### Summary

#### Ticket Link

2021-11-17 19:56 UTC, cwarnermm reviewed
Thanks! I've provided feedback inline.

2021-11-17 19:56 UTC, cwarnermm commented on source/configure/configuration-settings.rst
> +This setting only affects email login. For domains to be restricted, you must also set Require Email Verification to ``True``.
```suggestion
This setting only affects email login. For domains to be restricted, you must also set `Require Email Verification <https://docs.mattermost.com/configure/configuration-settings.html#require-email-verification>`__ to ``true``. 
```

2021-11-17 19:56 UTC, cwarnermm commented on source/messaging/team-settings.rst
> +Users without a matching domain on the team prior to the domain being specified will not be removed after the domain is added. For domains to be restricted, **System Console > Authentication > Email
```suggestion
Users without a matching domain on the team prior to the domain being specified will not be removed after the domain is added. For domains to be restricted, **System Console > Authentication > Email > Require Email Verification** must be set to ``true``. 
```

2021-11-17 19:56 UTC, cwarnermm commented on source/configure/configuration-settings.rst
> +This setting only affects email login. For domains to be restricted, you must also set Require Email Verification to ``True``.
Added a direct link to the config setting

2021-11-18 10:08 UTC, DSchalla requested changes
Two minor change proposals, LGTM otherwise

2021-11-18 10:08 UTC, DSchalla commented on source/messaging/team-settings.rst
> +Users without a matching domain on the team prior to the domain being specified will not be removed after the domain is added. For domains to be restricted, **System Console > Authentication > Email
```suggestion
Users without a matching domain on the team prior to the domain being specified will not be removed after the domain is added. For servers with email authentication **System Console > Authentication > Email > Require Email Verification** must be set to ``true`` for domain restrictions to be effective.
```

2021-11-18 10:08 UTC, DSchalla commented on source/configure/configuration-settings.rst
> +This setting only affects email login. For domains to be restricted, you must also set `Require Email Verification <https://docs.mattermost.com/configure/configuration-settings.html#require-email-ver
```suggestion
This setting only affects email login. For domains restrictions to be effective, you must also set `Require Email Verification <https://docs.mattermost.com/configure/configuration-settings.html#require-email-verification>`__ to ``true``. 
```

2021-11-19 16:49 UTC, cwarnermm approved these changes
Thanks!

2021-11-22 10:01 UTC, DSchalla approved these changes

2021-11-22 19:34 UTC, justinegeffen reviewed
Some minor corrections prior to merge. :)

2021-11-22 19:34 UTC, justinegeffen commented on source/configure/configuration-settings.rst
> +This setting only affects email login. For domains restrictions to be effective, you must also set `Require Email Verification <https://docs.mattermost.com/configure/configuration-settings.html#requi
```suggestion
This setting only affects email login. For domain restrictions to be effective, you must also set `Require Email Verification <https://docs.mattermost.com/configure/configuration-settings.html#require-email-verification>`__ to ``true``.
```

2021-11-22 19:34 UTC, justinegeffen commented on source/messaging/team-settings.rst
> +Specifying domains in this setting prevents users from joining the team when their email domain is not on the list. Only users that have an email domain matching the defined domains may join the team
```suggestion
Specifying domains in this setting prevents users from joining the team when their email domain is not on the list. Only users that have an email domain matching the defined domains may join the team.
```

2021-11-22 19:34 UTC, justinegeffen commented on source/messaging/team-settings.rst
> +Users without a matching domain on the team prior to the domain being specified will not be removed after the domain is added. For servers with email authentication **System Console > Authentication
```suggestion
Users without a matching domain on the team prior to the domain being specified will not be removed after the domain is added. For servers with email authentication **System Console > Authentication > Email > Require Email Verification** must be set to **true** for domain restrictions to be effective.
```

2021-11-22 19:35 UTC, justinegeffen approved these changes

2021-11-22 19:40 UTC, merged