Update mobile-app-changelog.md
mattermost/docs pull request #5393
Opened 2022-01-31 14:11 UTC by amyblais

2022-02-08 16:09 UTC, enahum requested changes

2022-02-08 16:14 UTC, amyblais commented on source/deploy/mobile-app-changelog.md
> + - Added the logic to create an Android app bundle along with the APK file on running the build command.
Removed.

2022-02-08 16:14 UTC, amyblais commented on source/deploy/mobile-app-changelog.md
> + - Fixed a crash issue on markdown table images.
Added now.

2022-02-08 16:23 UTC, enahum approved these changes

2022-02-08 22:32 UTC, esethna commented on source/deploy/mobile-app-changelog.md
> +#### All apps
Were there any other crash fixes? I think @jgilliam17 mentioned some?

2022-02-10 17:32 UTC, anurag6713 approved these changes

2022-02-16 13:56 UTC, merged