Update cloud-data-export.rst
mattermost/docs pull request #5410
Opened 2022-02-09 16:23 UTC by justinegeffen

Update for: https://mattermost.atlassian.net/browse/MM-41264

2022-02-09 18:51 UTC, jasonblais requested changes
Thanks @justinegeffen! Given this page is designs for Self-Hosted admins who are looking to migrate to Cloud, I wonder if there is another location we could add this information to, which caters to any Cloud users? (e.g. those coming from Slack)

2022-02-09 18:51 UTC, jasonblais commented on source/manage/cloud-data-export.rst
> +Currently, Mattermost Cloud data resides in the aws-us-east-1 region. Please contact feedback-cloud[at]mattermost.com to share feedback about additional data residencies with the product team.
```suggestion
Currently, Mattermost Cloud data resides in the `aws-us-east-1` region, located in Virginia, United States. Please contact the product team via feedback-cloud[at]mattermost.com if you have additional data residency requirements.
```

2022-02-14 13:54 UTC, justinegeffen commented
> Thanks @justinegeffen! Given this page is designs for Self-Hosted admins who are looking to migrate to Cloud, I wonder if there is another location we could add this information to, which caters to any Cloud users? (e.g. those coming from Slack)

We could also add it to: https://docs.mattermost.com/onboard/migrating-to-mattermost.html as a general note.

2022-02-14 17:23 UTC, jasonblais commented
(I'm happy to submit a PR for it for review)

2022-02-14 18:41 UTC, justinegeffen commented
Ah, gotcha. Sorry for the misunderstanding there! That draft looks good to me; let me find the right place for it to live.

2022-03-01 15:21 UTC, closed without merging