Updated Dev Console tool access
mattermost/docs pull request #5456
Opened 2022-03-04 21:11 UTC by cwarnermm

Documentation for https://github.com/mattermost/docs/issues/5420 
- Updated the steps to access the Dev Console tools
- Applied Style Guide & text format updates

2022-03-14 23:34 UTC, svelle requested changes

2022-03-14 23:34 UTC, svelle commented on source/install/desktop-app-install.rst
> +3. To run Mattermost, open **Dash** (located at the top left corner), enter **mattermost**, then select the Mattermost icon.
I wouldn't put concrete steps on how to run a linux app into this doc. We don't know what window manager the user is running so we can't assume that these are the correct steps to run the app.

2022-03-14 23:34 UTC, svelle commented on source/install/desktop-app-install.rst
> +- Linux: Open the File Manager, go to the ``~/.config/Mattermost`` folder, then delete the ``Local Storage`` folder.
Linux filemanagers hide folders starting with a period by default. I'd recommend deleting them using the terminal using `rm -rf ~/.config/Mattermost` or similar.

2022-03-14 23:34 UTC, svelle commented on source/install/desktop-app-install.rst
> +- Linux: Open the file manager, go to the ``~/.config/Mattermost`` folder, then delete the ``IndexedDB`` folder and the ``Cookies`` and ``Cookies-journal`` files.
same here

2022-03-14 23:34 UTC, svelle commented on source/install/desktop-app-install.rst
> +When you have more than one server added to the Desktop App, you need to change the ``0`` in the command above to the number corresponding to the server you want to open in the Developer Tools Consol
This step isn't really needed anymore since the dev console can simply be opened through the desktop app in the "View" dropdown.

2022-03-14 23:34 UTC, svelle commented on source/install/desktop-app-install.rst
> +3. To run Mattermost, open **Dash** (located at the top left corner), enter **mattermost**, then select the Mattermost icon.
see comment below

2022-03-17 12:55 UTC, cwarnermm commented
@svelle - I've applied the changes you recommended. This PR is ready for your review. Thanks!

2022-03-17 12:58 UTC, svelle approved these changes
Looks all good to me now! :)

2022-03-17 13:12 UTC, merged