Update sharing-boards.rst
mattermost/docs pull request #5472
Opened 2022-03-13 15:40 UTC by justinegeffen

Revised steps to access share link.

2022-03-14 03:14 UTC, wuwinson requested changes

2022-03-14 03:14 UTC, wuwinson commented on source/boards/sharing-boards.rst
>  3. Set the toggle on to **Publish to web and share this board with anyone**.
```suggestion
3. Copy the internal link to **Share an editable view with users who have permissions to the board**.
-- OR --
4. Switch to the Publish tab and set the toggle on to **Publish and share a "read-only" link with everyone on the web**.
```

2022-03-14 03:14 UTC, wuwinson commented on source/boards/sharing-boards.rst
>  4. Copy the link provided.
```suggestion
5. Copy the link provided.
```

2022-03-14 03:14 UTC, wuwinson commented on source/boards/sharing-boards.rst
>  3. Set the toggle on to **Publish to web and share this board with anyone**.
There's an extra "internal link" option in the Share modal. Maybe using numbered bullet points isn't the best with the "OR" option, but added details on the new functionality. Feel free to fix up the formatting as you see fit @justinegeffen.

2022-03-14 15:59 UTC, cwarnermm approved these changes
I've provided a couple of suggestions to consider. Approving for expediency.

2022-03-14 15:59 UTC, cwarnermm commented on source/boards/sharing-boards.rst
> +2. On the top-right of the board select **Share board**.
```suggestion
2. Select **Share board** in the top-right corner of the board.
```

2022-03-14 15:59 UTC, cwarnermm commented on source/boards/sharing-boards.rst
> +   * Copy the internal link to **Share an editable view with users who have permissions to the board**.
```suggestion
   * On the **Share** tab, you can share an editable view link with users who have permissions to the board.
```

2022-03-14 15:59 UTC, cwarnermm commented on source/boards/sharing-boards.rst
> +   * Switch to the **Publish** tab and set the toggle on to **Publish and share a "read-only" link with everyone on the web**.
```suggestion
   * On the **Publish** tab, you can share a read-only link online with everyone.
```

2022-03-14 21:17 UTC, chenilim approved these changes
Looks good, but we should document the System Console setting if not already and link to it.

2022-03-14 21:17 UTC, chenilim commented on source/boards/sharing-boards.rst
> +   * On the **Publish** tab, you can share a read-only link online with everyone.
The "Enable Publicly-Shared Boards" must be turned on in the System Console for this option to be enabled (it's currently off by default). Just checking that this is covered somewhere already. Suggest linking to it if so.

2022-03-15 03:47 UTC, wuwinson approved these changes
Looks good to me! And good point @chenilim - I don't think we have any documentation on the "Enable Publicly-Shared Boards" setting, but we should get that in.

@justinegeffen below are the steps for your reference:

To enable the share button on Boards:
From the app switcher, go to System Console > Mattermost Boards (Under "Plugins") > set "Enable Publicly-Shared Boards" to "True"
![Screen Shot 2022-03-14 at 11 40 15 PM](https://user-images.githubusercontent.com/93531870/158301732-78f70afd-8271-4873-8132-c693ff64cb11.png)

2022-03-15 14:09 UTC, merged