Update setting-up-playbooks.rst
mattermost/docs pull request #5473
Opened 2022-03-14 18:21 UTC by justinegeffen

Added content for import, export, duplicate.

2022-03-14 18:21 UTC, justinegeffen commented on source/playbooks/setting-up-playbooks.rst
> +You can also import playbooks between teams. From the **Playbooks** screen, select **Import**. Choose the team you're importing to, then select the JSON file.
@crspeller, could you help with any missing content/context here. Thank you!

2022-03-15 12:46 UTC, justinegeffen commented
@crspeller, if you have a moment to review this it'd be awesome. :)

2022-03-15 13:24 UTC, cwarnermm approved these changes

2022-03-15 16:31 UTC, crspeller requested changes

2022-03-15 16:34 UTC, justinegeffen commented on source/playbooks/setting-up-playbooks.rst
> +Lastly, if you want to create a backup of your playbook in JSON format, you can export it. To do this from the Playbooks screen, select the **...** under **Actions** and then select **Export**. Save
Ah interesting. Tao mentioned a use case around that but I may very well have misunderstood. :)

2022-03-15 16:36 UTC, justinegeffen commented
Thanks, @crspeller! I've revised it to be simpler. The release announcement provides a good use case.

2022-03-15 16:38 UTC, crspeller requested changes

2022-03-15 16:38 UTC, crspeller commented on source/playbooks/setting-up-playbooks.rst
> +You can import playbooks between teams. From the **Playbooks** screen, select **Import**. Choose the team you're importing to, then select the JSON file. You can also export any playbook to JSON to e
Not sure what `between teams` means here. You can import playbooks.

2022-03-15 16:39 UTC, justinegeffen commented on source/playbooks/setting-up-playbooks.rst
> +You can import playbooks between teams. From the **Playbooks** screen, select **Import**. Choose the team you're importing to, then select the JSON file. You can also export any playbook to JSON to e
```suggestion
To import a playbook, go to the **Playbooks** screen, select **Import**. Choose the team you're importing to, then select the JSON file. You can also export any playbook to JSON to easily share with other Mattermost servers.
```

2022-03-15 16:40 UTC, crspeller approved these changes

2022-03-15 16:42 UTC, justinegeffen commented
Thanks for the super-quick review, @crspeller! :)

2022-03-15 16:58 UTC, merged