Update self-managed-changelog.md
mattermost/docs pull request #5505
Opened 2022-03-30 14:27 UTC by amyblais

2022-04-04 13:24 UTC, isacikgoz approved these changes

2022-04-04 15:13 UTC, agnivade approved these changes

2022-04-05 17:01 UTC, mkraft approved these changes

2022-04-05 19:47 UTC, esethna commented on source/install/self-managed-changelog.md
> + - The **Actions** menu was restructured to reduce clutter.
cc// @aaronrothschild on copy here

2022-04-05 19:48 UTC, esethna commented on source/install/self-managed-changelog.md
> + - Added nested previews for permalinks.
cc// @laneycs on copy here

2022-04-05 19:49 UTC, esethna commented on source/install/self-managed-changelog.md
> + - Improved performance of Collapsed Reply Threads when backend is enabled but frontend is disabled.
Improved performance of Collapsed Reply Threads when `ThreadAutoFollow` is enabled but `CollapsedThreads` is disabled.

2022-04-05 19:50 UTC, esethna commented on source/install/self-managed-changelog.md
> + - [Collapsed Reply Threads](https://docs.mattermost.com/messaging/organizing-conversations.html) is currently in beta. Before enabling the feature, please ensure you are well versed in the [known is
...promoted to general availability in Q2 2022

2022-04-05 19:51 UTC, esethna commented on source/install/self-managed-changelog.md
> + - The default for ``ThreadAutoFollow`` has been changed to ``true``. This does not affect existing configurations where this value is already set to ``false``.
We don't really need this to be an important upgrade note since it doesn't affect existing installs

2022-04-05 19:52 UTC, esethna approved these changes
Approving with some suggestions above

2022-04-05 21:05 UTC, mickmister commented on source/install/self-managed-changelog.md
> + - The App Framework allows developers to build integrations with Mattermost that seamlessly work across Mattermost’s desktop and mobile clients, can be coded in any language developers are comfortab
```suggestion
 - The App Framework allows developers to build integrations with Mattermost that seamlessly work across Mattermost’s desktop and mobile clients. Apps can be developed using any programming language, as opposed to plugins which must be developed in Go.
```

2022-04-06 02:00 UTC, marianunez approved these changes

2022-04-06 21:07 UTC, jasonblais requested changes
Looking good,
 - for improvements, recommend starting with the benefit/value to the user 
 - recommend adding links to further details/info about a feature or the change. Think from the perspective of someone not familiar with Mattermost and reading the changelog for the first time. They may wonder what "feature flags" or "playbook retrospective metrics" are.

2022-04-06 21:15 UTC, cwarnermm commented on source/install/self-managed-changelog.md
> + - The Apps Framework protocol for binding/form submissions has changed, by separating the single `call` into separate `submit`, `form`, `refresh` and `lookup` calls. If any users have created their
@mickmister has confirmed that a docs update is needed for this update via https://github.com/mattermost/mattermost-webapp/pull/9263#issuecomment-1089362136

2022-04-06 21:16 UTC, cwarnermm commented on source/install/self-managed-changelog.md
> + - The App Framework allows developers to build integrations with Mattermost that seamlessly work across Mattermost’s desktop and mobile clients. Apps can be developed using any programming language,
https://developers.mattermost.com/integrate/apps/

2022-04-06 21:16 UTC, cwarnermm commented on source/install/self-managed-changelog.md
> + - Added retrospective metrics to track up to four key metrics that indicate performance of every run.
@justinegeffen - Can you help provide a link to the docs for this update, please?

2022-04-06 21:18 UTC, cwarnermm commented on source/install/self-managed-changelog.md
> + - Channel admins can now configure certain actions to be executed automatically based on trigger conditions without writing any code.
A PR for Channels is in progress: https://github.com/mattermost/docs/pull/5545
Justine is drafting a Playbook update as well. PR coming soon.

2022-04-06 21:19 UTC, cwarnermm commented on source/install/self-managed-changelog.md
> + - Added a ``Automatically Follow Threads`` configuration setting to the **System Console** to expose the ``threadAutoFollow`` config setting to the User Interface.
Documented via https://github.com/mattermost/docs/pull/5520

2022-04-06 21:21 UTC, cwarnermm commented on source/install/self-managed-changelog.md
> + - Feature flags are now automatically refreshed when the server undergoes a restart.
https://developers.mattermost.com/contribute/server/feature-flags/

2022-04-06 21:26 UTC, cwarnermm commented on source/install/self-managed-changelog.md
> + - Brazilian Portuguese language support was downgraded to Beta.
Historically, we've documented language support downgrades under Improvements > User Interface (UI) in the changelogs. I appreciate that where this information is included today could be misleading (but we don't necessarily have a better home for this content given the current structure of the the changelog sections).

2022-04-06 21:27 UTC, cwarnermm commented on source/install/self-managed-changelog.md
> +#### User Interface (UI)
@amyblais - I'm happy to help with this ask -- either the initial pass or a follow-up editorial pass. Just let me know how best I can assist.

2022-04-07 11:32 UTC, jasonblais approved these changes
Thanks for the recent updates :+1:

I would encourage adding a link for each highlighted feature (namely triggers and playbook retrospectives) for further details, else LGTM

2022-04-07 15:03 UTC, larkox approved these changes

2022-04-07 15:18 UTC, Willyfrog approved these changes
Minor comment but looking good 👍🏼

2022-04-07 15:18 UTC, Willyfrog commented on source/install/self-managed-changelog.md
> + - The default for [``ThreadAutoFollow``](https://docs.mattermost.com/configure/configuration-settings.html#automatically-follow-threads) has been changed to ``true``. This does not affect existing c
@esethna should we advise people to turn it on if they have it to off?

2022-04-11 19:56 UTC, esethna commented on source/install/self-managed-changelog.md
> + - The default for [``ThreadAutoFollow``](https://docs.mattermost.com/configure/configuration-settings.html#automatically-follow-threads) has been changed to ``true``. This does not affect existing c
Good point, I'll add a note

2022-04-12 13:25 UTC, merged