Cloud Changelog - Apr 13
mattermost/docs pull request #5527
Opened 2022-04-04 13:45 UTC by amyblais

2022-04-05 03:44 UTC, agnivade commented on source/install/cloud-changelog.md
> + - The elasticsearch indexing job is resumable now. Stopping a server while the job is running will put the job in pending status and will resume the job when the server starts. The job can still be
Elasticsearch isn't used in cloud. So it can be removed.

2022-04-05 03:44 UTC, agnivade commented on source/install/cloud-changelog.md
> + - Added a new stats field under the channel object for graphql.
GraphQL is still behind a feature flag so this can be removed.

2022-04-05 03:44 UTC, agnivade commented on source/install/cloud-changelog.md
> + - Elasticsearch and Bleve indexing have been revamped to be much more efficient and faster. The config parameter ``BulkIndexingTimeWindowSeconds`` for both elasticsearch and bleve is now deprecated
Same. Is not applicable for cloud.

2022-04-05 12:28 UTC, isacikgoz approved these changes

2022-04-05 13:15 UTC, cwarnermm approved these changes

2022-04-05 17:04 UTC, mkraft requested changes

2022-04-05 17:04 UTC, mkraft commented on source/install/cloud-changelog.md
> + - Added a new Activity & Insights feature, consisting of usage and behaviour data, which helps Enterprises further increase productivity of their employees through Mattermost functionality.
Although we've started merging things in for this feature behind a feature flag it definitely isn't ready for people to start enabling it. I doubt it makes sense to list this.

2022-04-05 17:05 UTC, amyblais commented on source/install/cloud-changelog.md
> + - Added a new Activity & Insights feature, consisting of usage and behaviour data, which helps Enterprises further increase productivity of their employees through Mattermost functionality.
Thanks, removed it!

2022-04-05 18:23 UTC, esethna commented on source/install/cloud-changelog.md
> + - ``api/v4/file/s3_test`` now requires ``FileSettings`` to be all set to run.
Are these two items categorized incorrectly?

2022-04-05 18:24 UTC, esethna approved these changes

2022-04-05 18:27 UTC, marianunez approved these changes

2022-04-05 18:40 UTC, amyblais commented on source/install/cloud-changelog.md
> + - ``api/v4/file/s3_test`` now requires ``FileSettings`` to be all set to run.
I moved them to "Administration" category.

2022-04-05 23:13 UTC, mkraft approved these changes

2022-04-06 07:05 UTC, agnivade approved these changes

2022-04-06 08:34 UTC, spirosoik approved these changes
lgtm

2022-04-06 14:20 UTC, gabrieljackson approved these changes

2022-04-06 21:11 UTC, jasonblais requested changes
Thanks Amy! Just a couple notes below

2022-04-06 21:11 UTC, jasonblais commented on source/install/cloud-changelog.md
> + - Updated the New Channel modal.
updated in what way?

2022-04-06 21:11 UTC, jasonblais commented on source/install/cloud-changelog.md
> + - Added another 'Active' filter for users and Admins in **System Console > User Management > Users**.
what's the value?

2022-04-06 21:11 UTC, jasonblais commented on source/install/cloud-changelog.md
> + - Removed cloud user limit count.
let's not include this one in the changelog (since this only impacts a few legacy customers)

2022-04-06 21:11 UTC, jasonblais commented on source/install/cloud-changelog.md
> +#### Administration
Are these relevant to Cloud admins?

2022-04-06 21:11 UTC, jasonblais commented on source/install/cloud-changelog.md
> + - Added another 'Active' filter for users and Admins in **System Console > User Management > Users**.
Also this is an admin feature

2022-04-06 21:11 UTC, jasonblais commented on source/install/cloud-changelog.md
> + - Added a configuration setting ``EmailSettings.EnableInactivityEmail`` to add the ability to toggle sending inactivity email notification to Admins.
Admin setting + let's start with the admin benefit/value

2022-04-07 11:29 UTC, jasonblais approved these changes

2022-04-13 12:33 UTC, merged