Cloud changelog - Apr 27
mattermost/docs pull request #5562
Opened 2022-04-19 12:40 UTC by amyblais

2022-04-19 13:29 UTC, marianunez approved these changes

2022-04-19 16:20 UTC, cwarnermm reviewed
Provided feedback inline.

2022-04-19 16:20 UTC, cwarnermm commented on source/install/cloud-changelog.md
> + - Fixed an issue where permalinks to Direct and Group Message posts did not show a preview.
Docs is moving away from capitalizing product features like Direct Messages or Group Messages.

2022-04-19 16:20 UTC, cwarnermm commented on source/install/cloud-changelog.md
> + - Fixed an issue where permalinks to Direct and Group Message posts did not show a preview.
```suggestion
 - Fixed an issue where permalinks to direct and group message posts did not show a preview.
```

2022-04-19 16:20 UTC, cwarnermm commented on source/install/cloud-changelog.md
> + - Fixed an issue where a mention badge was present when marking a root post with a mention as unread on the right-hand side with Collapsed Reply Threads enabled.
I'm not clear on what we've changed/fixed in this situation. Have we hidden the mention badge under these circumstances?

2022-04-19 16:20 UTC, cwarnermm commented on source/install/cloud-changelog.md
> + - Fixed an issue where copy links did not fire a track callback until the copy link was actually clicked.
What would this look like to an end user who is unfamiliar with track callbacks?

2022-04-19 16:20 UTC, cwarnermm commented on source/install/cloud-changelog.md
> + - Fixed an issue where the custom emoji "Next" button was out of view when a banner was present.
```suggestion
 - Fixed an issue where the custom emoji **Next** button was out of view when a banner was present.
```

2022-04-19 17:42 UTC, amyblais commented on source/install/cloud-changelog.md
> + - Fixed an issue where a mention badge was present when marking a root post with a mention as unread on the right-hand side with Collapsed Reply Threads enabled.
I clarified the text.

2022-04-19 17:43 UTC, amyblais commented on source/install/cloud-changelog.md
> + - Fixed an issue where copy links did not fire a track callback until the copy link was actually clicked.
I removed this as it's likely not important to add here.

2022-04-19 19:09 UTC, agnivade commented on source/install/cloud-changelog.md
> + - Added a new config cleanup job to regularly remove outdated entries from the database. The threshold for this setting can be adjusted with ``JobSettings.CleanupConfigThresholdDays``.
Added a new cleanup job to regularly remove outdated config entries from the database. The threshold ..

2022-04-20 04:46 UTC, agnivade approved these changes

2022-04-20 12:59 UTC, jasonblais requested changes

2022-04-20 12:59 UTC, jasonblais commented on source/install/cloud-changelog.md
> + - Added a new cleanup job to regularly remove outdated config entries from the database. The threshold for this setting can be adjusted with ``JobSettings.CleanupConfigThresholdDays``.
Not for Cloud

2022-04-20 12:59 UTC, jasonblais commented on source/install/cloud-changelog.md
> + - Bumped Go to v1.18.
Not for Cloud

2022-04-20 12:59 UTC, jasonblais commented on source/install/cloud-changelog.md
> + - Added ``fromWebhook`` property to the webapp plugin API.
Not for Cloud

2022-04-20 12:59 UTC, jasonblais commented on source/install/cloud-changelog.md
> + - Added a new API endpoint ``POST /api/v4/users/{user_id}/teams/{team_id}/threads/{thread_id}/set_unread/{post_id}`` to set a thread as unread by post id.
For this and the other API change that remains, I would change this section header to `#### API changes for Custom Integrations`

2022-04-20 12:59 UTC, jasonblais commented on source/install/cloud-changelog.md
> + - Improved the performance of configuration read/writes if the configuration is stored on a database.
Not relevant for Cloud

2022-04-20 12:59 UTC, jasonblais commented on source/install/cloud-changelog.md
> + - Fixed an issue where the ``UpdateUser`` API endpoint required a ``create_at`` field.
I would move this to the above API changes section

2022-04-20 13:17 UTC, jasonblais approved these changes

2022-04-21 07:15 UTC, spirosoik approved these changes

2022-04-25 15:57 UTC, dontoisme approved these changes

2022-04-26 14:25 UTC, cwarnermm reviewed
Thanks! Feedback provided inline.

2022-04-26 14:25 UTC, cwarnermm commented on source/install/cloud-changelog.md
> + - Fixed an issue where a mention badge was unexpectedly present in addition to the thread item bolding when marking a root post with a mention as unread on the right-hand side with Collapsed Reply T
```suggestion
 - Fixed an issue when Collapsed Reply Threads are enabled where marking a root post with a mention as unread displayed both a mention badge and the thread item being bolded.
```

2022-04-26 20:08 UTC, dontoisme approved these changes

2022-04-26 20:59 UTC, esethna approved these changes

2022-04-28 12:42 UTC, merged