Playbooks: Plan limits
mattermost/docs pull request #5689
Opened 2022-06-01 18:45 UTC by justinegeffen

Updated content to specify which features are limited to specific plans.

@agarciamontoro, could you let me know if there's any functionality/limits that I overlooked? Thank you!

2022-06-01 19:08 UTC, cwarnermm approved these changes

2022-06-06 10:04 UTC, agarciamontoro requested changes
Sorry for the delay, @justinegeffen.

There's also the timeline and retrospective features:
![image](https://user-images.githubusercontent.com/3924815/172140244-e40290a1-d1c2-4413-a34c-6403ef71126b.png)
![image](https://user-images.githubusercontent.com/3924815/172140370-951abaa9-5312-4a6e-ba97-1412f91fd348.png)

2022-06-06 20:10 UTC, justinegeffen commented
> Sorry for the delay, @justinegeffen.
> 
> There's also the timeline and retrospective features

Thank you! That's the first file that's been edited - we don't have specific sections for timeline and retrospectives, it's all rolled into the metrics and goals page. But I have updated the note for extra clarity.

2022-06-07 08:09 UTC, agarciamontoro approved these changes
Oooh, I see. Thank you for the context, I had just looked at the green lines in the first review :joy:

2022-06-08 13:49 UTC, merged