Cloud changelog - Sept 1st
mattermost/docs pull request #5859
Opened 2022-08-25 12:57 UTC by amyblais

2022-08-25 13:08 UTC, cwarnermm reviewed
Feedback provided inline

2022-08-25 13:08 UTC, cwarnermm commented on source/install/cloud-changelog.md
> +Added new API endpoint ``GET /api/v4/users/me/top/dms`` to get users' Direct Message channel insights.
```suggestion
- Added new API endpoint ``GET /api/v4/users/me/top/dms`` to get users' Direct Message channel insights.
```

2022-08-25 13:08 UTC, cwarnermm commented on source/install/cloud-changelog.md
> + - The runs and playbooks in the Playbooks left-hand sidebar does not have dot-menus that allow interaction with each item [MM-44752](https://mattermost.atlassian.net/browse/MM-44752).
```suggestion
 - The runs and playbooks in the Playbooks left-hand sidebar don't have dot-menus that allow interaction with each item [MM-44752](https://mattermost.atlassian.net/browse/MM-44752).
```

2022-08-26 14:53 UTC, dontoisme approved these changes

2022-08-26 14:57 UTC, marianunez approved these changes
Minor suggestion below

2022-08-26 14:57 UTC, marianunez commented on source/install/cloud-changelog.md
> + - Fixed an issue for the customer portal where the completed Company Information screen read "Provide your company name and address".
```suggestion
 - Fixed an issue in the System Console > Subscription where the completed Company Information screen read "Provide your company name and address".
```

2022-08-26 15:28 UTC, johndavidlugtu approved these changes

2022-08-26 17:08 UTC, wuwinson requested changes
@amyblais Made a few tweaks. Everything else looks good!

2022-08-26 17:08 UTC, wuwinson commented on source/install/cloud-changelog.md
> + - Fixed a bug where the "new" button in Kanban columns didn't always work.
```suggestion
 - Fixed a bug where the "new" button in Kanban columns didn't always work [issue-focalboard-3600](https://github.com/mattermost/focalboard/issues/3600).
```

2022-08-26 17:08 UTC, wuwinson commented on source/install/cloud-changelog.md
> + - On Boards, selecting the **+ New** button below a column on the Kanban view doesn't always create a new card. As a workaround, set a new default card template by going to the dropdown menu from th
```suggestion
```

2022-08-26 17:12 UTC, wuwinson approved these changes
LGTM!

2022-08-29 12:55 UTC, cwarnermm reviewed
Provided feedback inline.

2022-08-29 12:55 UTC, cwarnermm commented on source/install/cloud-changelog.md
> + - Fixed a bug where the "new" button in Kanban columns didn't always work [issue-focalboard-3600](https://github.com/mattermost/focalboard/issues/3600).
```suggestion
 - Fixed a bug where the **New** button in Kanban columns didn't always work [issue-focalboard-3600](https://github.com/mattermost/focalboard/issues/3600).
```

2022-08-29 13:21 UTC, mkraft requested changes

2022-08-29 13:21 UTC, mkraft commented on source/install/cloud-changelog.md
> + - Added most active Direct Message channels, new top Playbooks, least active channels, and new team members widgets to Insights.
```suggestion
 - Added new Insights widgets: Most Active DMs, Top Playbooks, Least Active Channels, and New Team Members.
```

2022-08-29 13:21 UTC, mkraft commented on source/install/cloud-changelog.md
> + - Added a new API endpoint ``GET /api/v4/users/me/top/dms`` to get users' Direct Message channel insights.
```suggestion
 - Added new API endpoints:
    - ``GET /api/v4/users/me/top/dms``
    - ``GET /api/v4/users/me/top/threads``
    - ``GET /api/v4/teams/:team_id/top/team_members``
    - ``GET /api/v4/teams/:team_id:/top/threads``
```

2022-08-29 13:27 UTC, mkraft approved these changes

2022-08-29 14:55 UTC, gabrieljackson approved these changes

2022-09-01 13:45 UTC, merged