Boards 7.3 and doc reorg
mattermost/docs pull request #5881
Opened 2022-09-07 19:40 UTC by justinegeffen

- Boards 7.3 content
- Doc reorg.

2022-09-13 20:41 UTC, wuwinson requested changes
Mostly bolded a bunch of text

2022-09-13 20:41 UTC, wuwinson commented on source/boards/groups-filter-sort.rst
> +Note: You must have at least one **Select** property on your board for filtering to work. Filtering by other property types such as **Person** or **Date** is not yet supported.
Does not appear as a callout in preview mode.

2022-09-13 20:41 UTC, wuwinson commented on source/boards/groups-filter-sort.rst
> +- **Doesn’t include**: Display all cards without any of the specified values from the “**Select** property.
```suggestion
- **Doesn’t include**: Display all cards without any of the specified values from the **Select** property.
```

2022-09-13 20:41 UTC, wuwinson commented on source/boards/calculations.rst
> +When you view a board in table, Kanban, or board view, you can use calculations to answer basic metric questions without needing to create complex reports. Hover over the bottom of a column to displa
```suggestion
When you view a board in table or board view, you can use calculations to answer basic metric questions without needing to create complex reports. Hover over the bottom of a column to display the **Calculate** feature, then select the arrow to open the menu options.
```

2022-09-13 20:41 UTC, wuwinson commented on source/boards/calculations.rst
> +When you view a board in table, Kanban, or board view, you can use calculations to answer basic metric questions without needing to create complex reports. Hover over the bottom of a column to displa
Kanban and board view are the same

2022-09-13 20:41 UTC, wuwinson commented on source/boards/share-and-collaborate.rst
> +The level of access to a board is determined by a user’s assigned board role.
Decided against using the table?

2022-09-13 20:41 UTC, wuwinson commented on source/boards/share-and-collaborate.rst
> +Board admins can manage team access to their board by selecting **Share** in the top-right corner of the board. On the dropdown next to **Everyone at… Team** option, select a minimum board role for e
```suggestion
Board admins can manage team access to their board by selecting **Share** in the top-right corner of the board. On the dropdown next to **Everyone at… Team** option, select a default board role for everyone on the team. 
```

2022-09-13 20:41 UTC, wuwinson commented on source/boards/share-and-collaborate.rst
> +Depending on the role selected, everyone on the team will have access to the board with a minimum of the permissions from the role selected. Users can get elevated permissions based on their individu
```suggestion
Depending on the role selected, everyone on the team will have access to the board with the permissions from the role selected. Users can get elevated permissions based on their individual board membership. The default team access for a newly created board is **None**, which means nobody on the team has access to the board.
```

2022-09-13 20:41 UTC, wuwinson commented on source/boards/share-and-collaborate.rst
> +To add individual users from the team as explicit members of the board, open the Share dialog on the board, search for individual team members, then assign a role to set their permissions for the boa
```suggestion
To add individual users from the team as explicit members of the board, open the **Share** dialog on the board, search for individual team members, then assign a role to set their permissions for the board. The role for individual board members overrides any role specified for team access.
```

2022-09-13 20:41 UTC, wuwinson commented on source/boards/share-and-collaborate.rst
> +- To remove a member from a board, open the **Share** dialog, select the role dropdown next to the user’s name, then select Remove member.
```suggestion
- To remove a member from a board, open the **Share** dialog, select the role dropdown next to the user’s name, then select **Remove member**.
```

2022-09-13 20:41 UTC, wuwinson commented on source/boards/share-and-collaborate.rst
> +Board admins can add a channel to a board to grant all its members Editor access. To do this, select **Share** in the top-right corner of the board, search for the channel name, and add it to the boa
```suggestion
Board admins can add a channel to a board to grant all its members Editor access. To do this, select **Share** in the top-right corner of the board, search for the channel name, and add it to the board as a user. The default role is Editor. Doing so also [links the board back to the channel](ADD URL to "Link a board to a channel"), where the board will appear on the channel RHS.
```

2022-09-13 20:41 UTC, wuwinson commented on source/boards/share-and-collaborate.rst
> +To unlink the channel from the board, open the **Share** dialog, select the role dropdown next to the channel’s name, then select Unlink.
```suggestion
To unlink the channel from the board, open the **Share** dialog, select the role dropdown next to the channel’s name, then select **Unlink**.
```

2022-09-13 20:41 UTC, wuwinson commented on source/boards/share-and-collaborate.rst
> +Only board admins manage user permissions on a board, including adding, changing, and removing members.
```suggestion
Only board admins can manage user permissions on a board, including adding, changing, and removing members.
```

2022-09-13 20:41 UTC, wuwinson commented on source/boards/share-and-collaborate.rst
> +Sharing boards publicly is disabled by default. This means that the Publish tab is not available from the Share dialog. To enable public board sharing:
```suggestion
Sharing boards publicly is disabled by default. This means that the **Publish** tab is not available from the **Share** dialog. To enable public board sharing:
```

2022-09-13 20:41 UTC, wuwinson commented on source/boards/share-and-collaborate.rst
> +Import and export a board
@justinegeffen This section should be moved to the "Migrate boards" section. There's also updated content for that as well that should be added there

2022-09-13 20:41 UTC, wuwinson commented on source/boards/navigate-boards.rst
> +If you're using Mattermost 7.0, open boards using the App Bar. If you don't see the Apps Bar to the right of your screen, you can access boards using the product menu in the top left corner of Matter
Recommend updating or removing this section. If a channel doesn't have linked boards, then you can't open Boards directly from the Apps Bar.

2022-09-13 20:41 UTC, wuwinson commented on source/boards/navigate-boards.rst
> +For users upgrading to Mattermost Boards v7.2 onwards:
Suggest putting this in a callout or differentiate it from the main text above.

2022-09-13 20:41 UTC, wuwinson commented on source/boards/navigate-boards.rst
> +- **Duplicate board**: Creates a copy of the board and all the cards on the board. The duplicated board will appear under the same category as the original board.
```suggestion
- **Duplicate board**: Creates a copy of the board and all the cards on the board. The duplicated board will appear under the same category as the original board. Board members from the original board are not migrated to the new board.
```

2022-09-14 08:42 UTC, justinegeffen commented on source/boards/share-and-collaborate.rst
> +The level of access to a board is determined by a user’s assigned board role.
Still adding the table. :)

2022-09-14 18:20 UTC, justinegeffen commented on source/boards/share-and-collaborate.rst
> +Board admins can add a channel to a board to grant all its members Editor access. To do this, select **Share** in the top-right corner of the board, search for the channel name, and add it to the boa
```suggestion
Board admins can add a channel to a board to grant all its members Editor access. To do this, select **Share** in the top-right corner of the board, search for the channel name, and add it to the board as a user. The default role is Editor. Doing so also `links the board back to the channel <https://docs.mattermost.com/boards/navigate-boards.html#link-a-board-to-a-channel>`_, where the board will appear on the channel RHS.
```

2022-09-14 18:32 UTC, justinegeffen commented
Thanks, @wuwinson, for the super-thorough review. I've addressed everything barring the table which I'll add shortly.

2022-09-14 19:29 UTC, justinegeffen commented on source/boards/overview.rst
> +Focalboard personal server and desktop
@wuwinson, I've added this based on some of the questions we've received about features that don't apply across the options. Can you think of any others to add?

2022-09-14 21:37 UTC, wuwinson requested changes
@justinegeffen Submitting these changes for now. Still have to go through Share, Navigate, and Migrate tomorrow.

2022-09-14 21:37 UTC, wuwinson commented on source/boards/work-with-cards.rst
> +Define a **Select** or **Multi-select** property
```suggestion
Define a "Select" or "Multi-select" property
```

2022-09-14 21:37 UTC, wuwinson commented on source/boards/work-with-cards.rst
> +Define a **Select** or **Multi-select** property
This header with bold text is showing up weird on the live preview. Maybe quotes will render better.

2022-09-14 21:37 UTC, wuwinson commented on source/boards/work-with-cards.rst
> +You can include a team member on a card by `mentioning them on a card <https://docs.mattermost.com/channels/mention-people.html>`__ the same way you would in Channels. Mentions are supported in the `
```suggestion
You can include a team member on a card by `mentioning them on a card <https://docs.mattermost.com/channels/mention-people.html>`__ the same way you would in Channels. Mentions are supported in the `Comments <https://docs.mattermost.com/boards/work-with-cards.html#comment-on-a-card>`_ and `Description <https://docs.mattermost.com/boards/work-with-cards.html#card-descriptions>`_ sections within a card. The team member you mention will receive a direct message notification from the boards bot with a link to the card you mentioned them on. To mention multiple team members, separate each name with a comma.
```

2022-09-14 21:37 UTC, wuwinson commented on source/boards/work-with-views.rst
> +You can change boards views to adjust how your cards are represented. To add a new view to a board, from the board header, select the menu next to the current view name. Scroll down and select **+ Ad
```suggestion
You can change board views to adjust how your cards are represented. To add a new view to a board, from the board header, select the menu next to the current view name. Scroll down and select **+ Add view**, then select the new visualization you’d like to use.
```

2022-09-15 19:02 UTC, merged