added alt text for embedded videos in the docs
mattermost/docs pull request #5918
Opened 2022-10-05 20:48 UTC by shikhar13012001

#### Summary

added alt text for embedded videos in the docs
#### Ticket Link

2022-10-05 20:48 UTC, mattermod commented
Hello @shikhar13012001,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

Per the [Mattermost Contribution Guide](https://developers.mattermost.com/contribute/getting-started/), we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**
Once you have signed the CLA, please comment with `/check-cla` and confirm that the CLA check is green.

This is a standard procedure for many open source projects.

Please let us know if you have any questions.

We are very happy to have you join our growing community! If you're not yet a member, please consider joining our [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets) to meet other contributors and discuss new opportunities with the core team.

2022-10-05 21:46 UTC, shikhar13012001 commented
/check-cla

2022-10-06 19:43 UTC, shikhar13012001 commented
/check-cla

2022-10-07 20:16 UTC, shikhar13012001 commented
/check-cla

2022-10-09 19:26 UTC, shikhar13012001 commented
Hi @cwarnermm, Can you please review my PR? Thanks !

2022-10-10 05:30 UTC, justinegeffen commented
Thanks for your PR, @shikhar13012001! We're in the process of reviewing Hacktoberfest PRs. Your contribution has been acknowledged as a Hacktoberfest PR. Thanks for your patience! :)

2022-10-11 14:14 UTC, cwarnermm requested changes
Thank you, @shikhar13012001! I've provided feedback inline.

2022-10-11 14:14 UTC, cwarnermm commented on source/archive/organizing-conversations-copy2.rst
> +      <iframe src="https://www.youtube.com/embed/hnD0Zj-mIbs" frameborder="0" allowfullscreen alt="video on organizing converstations copy 2" style="position: absolute; top: 0; left: 0; width: 100%;
```suggestion
      <iframe src="https://www.youtube.com/embed/hnD0Zj-mIbs" frameborder="0" allowfullscreen alt="Video on organizing Mattermost conversations" style="position: absolute; top: 0; left: 0; width: 100%; height: 95%;"></iframe>
```

2022-10-11 14:14 UTC, cwarnermm commented on source/archive/organizing-conversations.rst
> +      <iframe src="https://www.youtube.com/embed/hnD0Zj-mIbs" alt="video on organizing converstion" frameborder="0" allowfullscreen style="position: absolute; top: 0; left: 0; width: 100%; height: 95
@shikhar13012001 - Source files located in the ``archive`` folder are no longer built into the product documentation and shouldn't be updated. Please revert this change.

2022-10-11 14:14 UTC, cwarnermm commented on source/manage/mmctl-command-line-tool.rst
> +      <iframe src="https://www.youtube.com/embed/zITNaPWP-80" alt="video on usage of mmctl command line tool" frameborder="0" allowfullscreen style="position: absolute; top: 0; left: 0; width: 100%;
```suggestion
      <iframe src="https://www.youtube.com/embed/zITNaPWP-80" alt="Video on what's new in the mmctl command line tool from Mattermost v6.0" frameborder="0" allowfullscreen style="position: absolute; top: 0; left: 0; width: 100%; height: 95%;"></iframe>
```

2022-10-11 14:14 UTC, cwarnermm commented on source/manage/mmctl-command-line-tool.rst
> +      <iframe src="https://www.youtube.com/embed/hmbSfSeWo4Y" alt="video for more information on what's changed in mmctl for Mattermost v6.0" frameborder="0" allowfullscreen style="position: absolute
```suggestion
      <iframe src="https://www.youtube.com/embed/hmbSfSeWo4Y" alt="Video for more information on what's changed in mmctl for Mattermost v6.0" frameborder="0" allowfullscreen style="position: absolute; top: 0; left: 0; width: 100%; height: 95%;"></iframe>
```

2022-10-11 14:14 UTC, cwarnermm commented on source/onboard/ad-ldap-groups-synchronization.rst
> +      <iframe src="https://www.youtube.com/embed/zyku2ibsG0M" alt="video overview about adding users to Mattermost with AD/LDAP" frameborder="0" allowfullscreen style="position: absolute; top: 0; lef
```suggestion
      <iframe src="https://www.youtube.com/embed/zyku2ibsG0M" alt="Video about adding users to Mattermost using AD/LDAP" frameborder="0" allowfullscreen style="position: absolute; top: 0; left: 0; width: 100%; height: 95%;"></iframe>
```

2022-10-17 18:03 UTC, cwarnermm commented
@shikhar13012001 - Please revert the single change applied to an archived docs source file.

2022-10-17 19:31 UTC, shikhar13012001 commented
@cwarnermm sorry for delay, I was busy with some personal college stuff, I have reverted the file as requested please review the file let, me know if you need further changes.

2022-10-19 12:25 UTC, cwarnermm approved these changes
Thank you, @shikhar13012001!

2022-10-19 12:40 UTC, merged