[GH-5951] Updates Authentication > SAML 2.0 Settings to New Format
mattermost/docs pull request #6102
Opened 2022-12-04 01:53 UTC by matthew-src

#### Summary

This PR updates the SAML 2.0 section of the Authentication settings to the new format. The description of these settings should get a technical review:

1. Ignore guest users when synchronizing with AD/LDAP
2. Override SAML bind data with AD/LDAP information
3. Enable encryption
4. Sign request - The default for this setting was not clear. Also, the current docs indicate it take a string value, but I think it is actually a boolean value.
5. Enable admin and Admin attribute - The functioning of these two settings is not clear to me.

#### Ticket Link

This PR partially addresses https://github.com/mattermost/docs/issues/5951.

2022-12-04 01:53 UTC, mattermod commented
Hello @matthew-src,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2022-12-05 14:28 UTC, cwarnermm commented
Thanks, @matthew-src! I've generated a preview of these updates. In that preview, there are formatting syntax issues with the following sections:
- Override SAML bind data with AD/LDAP information (note text bullets)
- Verify signature (table)
- Service provider login URL (table)
- Sign request (table)
- Enable admin attribute (table)
- Login button text (table)

@mkraft - Would a member of the Suite Users team be available to technically review the SAML 2.0 config setting documentation for accuracy, please?

2022-12-05 14:44 UTC, matthew-src commented
>     * Override SAML bind data with AD/LDAP information (note text bullets)
> 
>     * Verify signature (table)
> 
>     * Service provider login URL (table)
> 
>     * Sign request (table)
> 
>     * Enable admin attribute (table)
> 
>     * Login button text (table)

I am sorry about that. I think the tables are all fixed now. I am not sure about the note text bullets. I think they just needed an extra space for indentation.

2022-12-06 12:57 UTC, matthew-src commented
I reviewed this again. **Now** the Override table is fixed.

2022-12-06 14:02 UTC, cwarnermm commented
Not a problem at all, @matthew-src! RST is a prescriptive file format and it can take a couple of runs to get the syntax working as expected. Generated previews help this process a lot!

You're doing such a great job with this project, and we're so incredibly thankful for your efforts.

2022-12-07 14:14 UTC, cwarnermm approved these changes
Thanks, @matthew-src! I'll hold off merging this one until Engineering's had an opportunity to review.

2022-12-07 23:06 UTC, mkraft requested changes

2022-12-08 00:29 UTC, matthew-src commented on source/configure/authentication-configuration-settings.rst
> +| - **true**: When syncing with the AD/LDAP server, Mattermost ignores Guest Users that have been deactivated and removed, and does not make any changes to them. Manage guest deactivation manually vi
Thank you, @mkraft, for reviewing this PR. If I understand correctly, I would try to summarize the functionality as:

When "Ignore guest users..." is set to **true**, syncing SAML-authenticated Mattermost accounts with AD/LDAP has no effect on Mattermost guest accounts that were created based on a Guest User AD/LDAP filter (see AD/LDAP filter setting). Changes to the user role or account deactivation must be done manually.

Now, just to be clear, would role changes be synced if "Ignore guest users..." is set to **false**?

2022-12-12 18:05 UTC, mkraft approved these changes

2022-12-12 18:36 UTC, cwarnermm commented
@matthew-src - Is there anything outstanding left on this PR from your perspective?

2022-12-12 19:46 UTC, mkraft commented on source/configure/authentication-configuration-settings.rst
> +| - **true**: When syncing with the AD/LDAP server, Mattermost ignores Guest Users that have been deactivated and removed, and does not make any changes to them. Manage guest deactivation manually vi
@matthew-src I realize now the description I put above was all about the AD/LDAP guest filters but I put it as a comment on the documentation for SAML ignore-guest boolean configuration.

Everything I said above is true for the AD/LDAP filter.

There's also a guest attribute for SAML which is documented correctly in product:

* changes to the guest attribute won't promote a user from guest to regular user
* changes to the guest filter *can* demote a regular user to a guest

If `IgnoreGuestsLdapSync` setting is `true` a user authenticating via SAML doesn't even need to exist in AD/LDAP and no values (ex. email, firstname, lastname) will be update in Mattermost for that user from AD/LDAP.

2022-12-13 00:15 UTC, matthew-src commented
I made a few changes, and some formatting fixes, but it all set now.

2022-12-13 00:16 UTC, matthew-src commented on source/configure/authentication-configuration-settings.rst
> +| - **true**: When syncing with the AD/LDAP server, Mattermost ignores Guest Users that have been deactivated and removed, and does not make any changes to them. Manage guest deactivation manually vi
Thank you, @mkraft . I will review the AD/LDAP settings based on your comment.

2022-12-13 16:16 UTC, merged