Message priority & acknowledgements
mattermost/docs pull request #6113
Opened 2022-12-08 21:14 UTC by cwarnermm

Documentation for: 
- https://github.com/mattermost/mattermost-server/pull/20875
- https://github.com/mattermost/mattermost-webapp/pull/10951

Includes end user workflows, system admin configuration setting details, and telemetry.

2022-12-09 16:09 UTC, Rishselva requested changes
Great work Carrie! 

The only piece of information that could be added is letting the user know that the settings are configurable.

2022-12-09 16:59 UTC, cwarnermm commented
Thanks, @Rishselva! Where would someone be able to change that 5 minute setting? Is that a config option we surface up in the System Console for admins?

2022-12-09 17:48 UTC, Rishselva commented
Yes, so if the admin goes to System Console > Posts they'll be able to see all the config options. 

<img width="1503" alt="Screen Shot 2022-12-09 at 12 47 53 PM" src="https://user-images.githubusercontent.com/113040380/206761903-8193039f-f50d-4895-a16f-34d81b935d36.png">

2022-12-12 12:15 UTC, justinegeffen approved these changes

2022-12-12 12:15 UTC, justinegeffen commented on source/channels/message-priority.rst
> +Set message priority (Beta)
```suggestion
Set message priority (beta)
```

2022-12-15 14:45 UTC, Rishselva requested changes
Looks great! 

Since we're cancelling v7.6 we might want to update the doc to say v7.7. Additionally, is there a reason why persistent notification is not included in this document?

2022-12-15 14:47 UTC, cwarnermm commented
Thanks, @Rishselva! Yes, I'll update this PR to change references from v7.6 to v7.7, and I'll update this PR to include the persistent notification functionality. It's not there yet because this PR focused on v7.6 functionality only and persistent notifications were scheduled for v7.7 at the time this PR was in flight.

2022-12-15 16:19 UTC, Rishselva commented
Hello! Recent update, we will not be including persistent notifications in the v7.7 release. We are okay to leave it out of this doc if its being released with v7.7.

2022-12-15 16:38 UTC, cwarnermm commented
Thanks, @Rishselva! I appreciate the update. I'll leave persistent notifications out of this PR. That feature will be documented closer to its scheduled release date.

2022-12-16 22:23 UTC, esethna commented
I will leave PM review to @Rishselva

2022-12-19 17:06 UTC, Rishselva approved these changes
Hello! Just reviewed the document and all of the information looks good! Thank you :)

2022-12-19 17:31 UTC, merged

2022-12-19 23:32 UTC, esethna reviewed
@cwarnermm @Rishselva I provided some suggestions for improvements on the doc page inline

2022-12-19 23:32 UTC, esethna commented on source/channels/message-priority.rst
> +From Mattermost v7.6, you can add a message priority label to root messages to make important messages requiring timely action or response more visible and less likely to be overlooked.
Mattermost v7.7? cc// @Rishselva @cwarnermm

2022-12-19 23:32 UTC, esethna commented on source/channels/message-priority.rst
> +Set message priority
Mobile can do this too, so we  should probably take the new tabbed approach to this content. cc// @cwarnermm @Rishselva

2022-12-19 23:32 UTC, esethna commented on source/channels/message-priority.rst
> +Set message priority (beta)
SInce it's in beta, how do people give feedback (ie the give feedback button in the pop-over)

2022-12-19 23:32 UTC, esethna commented on source/channels/message-priority.rst
> +Set message priority (beta)
How do admins disable it if desired?

2022-12-19 23:32 UTC, esethna commented on source/channels/message-priority.rst
> +Set message priority (beta)
Can we try to answer the question of "when should I use a message priority label"? ie we don't want people to abuse it. So providing some example use cases for the priority labels and ack might be useful in the docs