Global drafts documentation
mattermost/docs pull request #6118
Opened 2022-12-12 20:29 UTC by cwarnermm

Documentation for:
- https://github.com/mattermost/mattermost-server/pull/20614
- https://github.com/mattermost/mattermost-webapp/pull/8869

2022-12-16 21:32 UTC, esethna commented
@Rishselva can you help take a first pass on reviewing this documentation?

2022-12-19 23:36 UTC, esethna requested changes

2022-12-19 23:36 UTC, esethna commented on source/channels/send-messages.rst
> +From Mattermost v7.6, when composing new messages, it's easy to return to a message in progress later. Draft messages are added to a **Drafts** view available at the top of the channel sidebar unless
7.7

2022-12-19 23:36 UTC, esethna commented on source/channels/send-messages.rst
> +From Mattermost v7.6, when composing new messages, it's easy to return to a message in progress later. Draft messages are added to a **Drafts** view available at the top of the channel sidebar unless
Actually the drafts tab will show no matter what the config setting is set to. The setting turns off whether the drafts are synced to the server/available across devices once mobile support is built

2022-12-19 23:36 UTC, esethna commented on source/configure/experimental-configuration-settings.rst
> +This setting saves in-progress message drafts in the Drafts view via the channel sidebar, and synchronizes draft messages across all supported Mattermost clients.
This setting ~~saves in-progress message drafts in the Drafts view via the channel sidebar, and~~ synchronizes draft messages across all supported Mattermost clients.

2023-01-06 16:03 UTC, justinegeffen commented on source/channels/send-messages.rst
> +From Mattermost v7.6, when composing new messages, it's easy to return to a message in progress later. Draft messages are added to a **Drafts** view available at the top of the channel sidebar unless
```suggestion
From Mattermost v7.7, when composing new messages, it's easy to return to a message in progress later. Draft messages are added to a **Drafts** view available at the top of the channel sidebar unless your system admin `disables global draft functionality </configure/experimental-configuration-settings.html#allow-synchronized-drafts>`__.
```

2023-01-06 16:04 UTC, justinegeffen commented on source/configure/experimental-configuration-settings.rst
> +This setting saves in-progress message drafts in the Drafts view via the channel sidebar, and synchronizes draft messages across all supported Mattermost clients.
```suggestion
This setting synchronizes draft messages across all supported Mattermost clients.
```

2023-01-06 16:04 UTC, justinegeffen commented on source/channels/send-messages.rst
> +By default, message drafts are synchronized on the Mattermost server AND accessible everywhere you access Mattermost, including a web browser or the desktop app with mobile support coming in a future
```suggestion
By default, message drafts are synchronized on the Mattermost server and are accessible everywhere you access Mattermost, including a web browser or the desktop app with mobile support coming in a future release. 
```

2023-01-06 16:05 UTC, justinegeffen approved these changes

2023-01-06 16:06 UTC, justinegeffen commented
> @Rishselva can you help take a first pass on reviewing this documentation?

I inadvertently removed @rishelva from the PR, and can't find them again. Sorry!

2023-01-14 03:36 UTC, esethna commented on source/configure/experimental-configuration-settings.rst
> +**True**: **(Default)** Global drafts are enabled, synchronized across clients, and draft messages are accessible through the Drafts view.
True: Message drafts are saved on the server and may be accessed from different clients. Users may still disable server synchronization of draft messages in Account Settings.

2023-01-14 03:37 UTC, esethna commented on source/configure/experimental-configuration-settings.rst
> +**False**: Global drafts are disabled.
False: Draft messages are only stored locally on each users device

2023-01-14 03:37 UTC, esethna approved these changes
@cwarnermm looks good, I just modified the proposed wording for the config setting as the drafts item is still available even if that is set to false (it just doesn't sync on the server)

2023-01-16 14:08 UTC, cwarnermm commented on source/configure/experimental-configuration-settings.rst
> +**False**: Global drafts are disabled.
```suggestion
**False**: Draft messages are only stored locally on each user's device.
```

2023-01-16 14:10 UTC, cwarnermm commented on source/configure/experimental-configuration-settings.rst
> +**True**: **(Default)** Global drafts are enabled, synchronized across clients, and draft messages are accessible through the Drafts view.
```suggestion
**True**: **(Default)** Message drafts are saved on the server and may be accessed from different clients. Users may still disable server synchronization of draft messages by going to **Settings > Advanced Settings**. 
```

2023-01-16 14:22 UTC, merged