Update deprecated-features.rst
mattermost/docs pull request #6344
Opened 2023-04-20 13:58 UTC by amyblais

2023-04-20 14:44 UTC, agnivade commented on source/install/deprecated-features.rst
> +- Removing support for PostgreSQL v10.
This is still on-hold at the moment.

2023-04-23 20:16 UTC, hanzei requested changes
LGTM, but ther

2023-04-23 20:16 UTC, hanzei commented on source/install/deprecated-features.rst
> +- Removing deprecated ``PermissionUseSlashCommands``.
```suggestion
- Removing deprecated ``PermissionUseSlashCommands``.
- Removing deprecated ``model.CommandArgs.Session``.
```

2023-04-23 20:16 UTC, hanzei commented on source/install/self-managed-changelog.md
> +5. Remove support for PostgreSQL v10.
```suggestion
4. Remove deprecated ``PermissionUseSlashCommands``.
5. Remove deprecated ``model.CommandArgs.Session``.
6. Remove support for PostgreSQL v10.
```

2023-05-03 19:02 UTC, hmhealey commented on source/install/self-managed-changelog.md
> +2. Remove ``ExperimentalSettings.PatchPluginsReactDOM``.
I'm double checking the first point here, but here's some more information for this change. 
```
2. Remove ``ExperimentalSettings.PatchPluginsReactDOM``. If this setting was previously enabled, confirm that:
    1. All Mattermost-supported plugins are updated to the latest versions.
    2. Any other plugins have been updated to support React 17. See the [Important Upgrade Notes](https://docs.mattermost.com/upgrade/important-upgrade-notes.html) for v7.7 for more information.
```
Also, I don't know if there's a better way to link directly to that note

2023-05-03 23:48 UTC, mickmister approved these changes

2023-05-05 15:21 UTC, wiersgallak approved these changes
Thanks, Amy. Looks good to me.

2023-05-05 15:35 UTC, hmhealey approved these changes

2023-05-08 21:19 UTC, wiggin77 commented on source/install/self-managed-changelog.md
> +3. Change advanced logging config format. Currently admins have to escape the JSON for advanced logging config in config.json, meaning it must be provided as a single line string.  The breaking chang
```suggestion
3. Three configuration fields have been added, `LogSettings.AdvancedLoggingJSON`, `ExperimentalAuditSettings.AdvancedLoggingJSON`, and `NotificationLogSettings.AdvancedLoggingJSON` which support multi-line JSON, escaped JSON as a string, or a filename that points to a file containing JSON.  The `AdvancedLoggingConfig` fields have been deprecated.
```

2023-05-09 17:06 UTC, cwarnermm approved these changes

2023-05-10 18:44 UTC, lieut-data commented
@amyblais / @cwarnermm, wondering if I can get your help adding a note about our new `public/` package? Something like the following:

```
The Mattermost public API for Go is now available as a distinctly versioned package. Instead of pinning a particular commit hash, use idiomatic Go to add this package as a dependency:

    go get github.com/mattermost/mattermost-server/server/public

This relocated Go API maintains backwards compatibility with Mattermost v7. Furthermore, the existing Go API previously at github.com/mattermost/mattermost-server/v6/model remains forward compatible with Mattermost v8, but may not contain newer features. Plugins do not need to be recompiled, but developers may opt in to using the new package to simplify their build process.

The new public package is shipping alongside Mattermost v8 as version 0.5.0 to allow for some additional code refactoring before releasing as v1 later this year.
```

2023-05-10 18:47 UTC, amyblais commented
@lieut-data Added now via https://github.com/mattermost/docs/pull/6344/commits/ab27245fb83b18baf079ce643d524cdf5aa826cb.

2023-05-15 15:16 UTC, wiggin77 commented on source/install/deprecated-features.rst
> +- Deprecating the ``AdvancedLoggingConfig`` fields.
```suggestion
- Deprecating the ``AdvancedLoggingConfig`` fields, and replacing them with ``AdvancedLoggingJSON`` fields which accept inline JSON or a filename.
```

2023-05-16 12:07 UTC, merged