Overhauled Ubuntu install steps via new page
mattermost/docs pull request #6358
Opened 2023-04-27 14:11 UTC by cwarnermm

This PR also:
- adds links for the new Ubuntu install page to the navigation pane and the deployment landing page for easy access
- removes the Ubuntu/Debian tab from the deployment landing page

@nab-77 - Please update this PR to indicate where the Marketing CTA links should be added. Thanks!

Note: The docs link via ``mattermost.com/download`` to the Ubuntu install docs will need to be updated from ``https://docs.mattermost.com/install/installing-ubuntu-2004-LTS.html`` to ``https://docs.mattermost.com/install/install-ubuntu.html``. Docs will create client-side redirects to ensure users with legacy Ubuntu install URLs are redirected to the correct page.

@emdecr - This PR is now ready for you to add the Marketing CTAs and code formatting. Thank you! Can we get your help with the note above too to update the website URL?

2023-04-27 14:24 UTC, nab-77 reviewed
Added copy-action items

2023-04-27 14:24 UTC, nab-77 commented on source/install/install-ubuntu.rst
> +    curl -o- https://deb.packages.mattermost.com/repo-setup.sh | sudo bash -s mattermost
@emdecr this is a cmd for the copy-action button

2023-04-27 14:24 UTC, nab-77 commented on source/install/install-ubuntu.rst
> +    sudo apt install mattermost -y
@emdecr this is the cmd for the copy-action button

2023-04-27 19:57 UTC, nab-77 requested changes

2023-04-27 19:57 UTC, nab-77 commented on source/install/install-ubuntu.rst
> +    - If you are running the Mattermost Server and database a single system, we recommend the `Mattermost Omnibus install method </install/installing-mattermost-omnibus.html>`__ as this greatly reduc
```suggestion
    - If you are running the Mattermost Server and database on a single system, we recommend the `Mattermost Omnibus install method </install/installing-mattermost-omnibus.html>`__ as this greatly reduces setup and ongoing maintenance.
```

2023-04-27 19:57 UTC, nab-77 commented on source/install/install-ubuntu.rst
> +	We recommend the `Mattermost Omnibus install method </install/installing-mattermost-omnibus.html>`__ over the ``deb`` signed package if you are running the Mattermost Server and database a single sy
```suggestion
	We recommend the `Mattermost Omnibus install method </install/installing-mattermost-omnibus.html>`__ over the ``deb`` signed package if you are running the Mattermost Server and database on a single system as this greatly reduces setup and ongoing maintenance.
```

2023-04-27 21:37 UTC, nab-77 approved these changes
Just needs the formatting/tracking from @emdecr

2023-04-28 18:39 UTC, emdecr commented
Missed the tag on this one; for some reason I'm not getting notifications for this PR via the GitHub <> MM integration 😞 

@cwarnermm I took a stab at the merge conflict in [deployment.rst](http://mattermost-docs-preview-pulls.s3-website-us-east-1.amazonaws.com/6358/guides/deployment.html) that was happening when I pulled from master, but worth a double-check to make sure that's all still good. Sorry if I mucked things up 😅 

Lemme know, if anything - TY!

2023-04-28 18:41 UTC, emdecr approved these changes

2023-04-28 19:27 UTC, emdecr commented
Oh and yes, once we merge, happy to change the URL on mm.com/download – just keep me in the loop or ping me, and I'll make the change.

2023-04-28 19:29 UTC, merged