Adding PostgreSQL DB slow query log
mattermost/docs pull request #6437
Opened 2023-05-29 13:03 UTC by cwarnermm

Troubleshooting for high-scale deployments

2023-06-16 16:05 UTC, coltoneshaw commented on source/deploy/high-scale-troubleshoot.rst
> +To enable slow query logging globally, change the following line in postgresql.conf and reload the page: ``log_min_duration_statement = 5000``. When you this value to ``5000``, PostgreSQL considers q
I'd set our suggestion to 1s for this, just to capture more. Anything longer than 1s really should be looked at.

2023-06-16 16:05 UTC, coltoneshaw commented on source/deploy/high-scale-troubleshoot.rst
> +  postgres=# ALTER DATABASE test SET log_min_duration_statement = 5000;
let's change `test` to `mattermost` and make a call out that the database name should be what you call it. 99% will be `mattermost`

2023-06-16 16:07 UTC, coltoneshaw requested changes

2023-06-16 16:07 UTC, coltoneshaw commented on source/deploy/high-scale-troubleshoot.rst
> +To enable slow query logging globally, change the following line in postgresql.conf and reload the page: ``log_min_duration_statement = 5000``. When you this value to ``5000``, PostgreSQL considers q
also, doing it this way requires a restart or a config reload. We have it reading as `reload the page` but it should be `restart postgres` which causes a short outage. 

Additionally, we could just have them run `SELECT pg_reload_conf();` to reload the config without a restart.

2023-06-16 16:08 UTC, coltoneshaw commented on source/deploy/high-scale-troubleshoot.rst
> +  ALTER DATABASE
This actually should be removed, it's just a hanging statement if used in this way.

2023-07-24 13:26 UTC, cwarnermm commented
Thanks @coltoneshaw! This docs PR is now ready for your final review.

2023-07-24 13:31 UTC, coltoneshaw approved these changes

2023-07-24 13:36 UTC, merged