Transitioning Boards to plugin
mattermost/docs pull request #6498
Opened 2023-06-26 20:41 UTC by cwarnermm

2023-06-27 17:58 UTC, esethna requested changes
@cwarnermm thanks for this! Hard to track all the changes so I just took a look in the preview env. Here's some high level thoughts:

1. I think the LHS section title for "Mattermost boards plugin" could be "Focalboard". The intro can describe that the focalboard plugin for Mattermost enables managing projects etc... with a link to the focalboard repo.

2. Then we can refer to all instances of the "Boards plugin" as the "Focalboard plugin" 

3. The plugin settings doc should have a subsection for enabling the plugin (since it's disabled by default in v8.0)

2023-06-28 18:21 UTC, cwarnermm commented
Hi @esethna! This PR should be ready for your final review. Thanks!

2023-08-24 13:35 UTC, mattermost-build commented
Error trying to update the PR.
Please do it manually.

2023-08-28 22:38 UTC, esethna approved these changes
Thank you Carrie!

2023-09-14 12:47 UTC, merged