users.json example added #6180-docs
mattermost/docs pull request #6680
Opened 2023-10-05 09:00 UTC by yesbhautik

#### Summary

I have added the users.json example snippet as per requirement [6180].

#### Ticket Link Fixes https://github.com/mattermost/docs/issues/6180

2023-10-05 09:00 UTC, mattermost-build commented
Hello @yesbhautik,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

Per the [Mattermost Contribution Guide](https://developers.mattermost.com/contribute/getting-started/), we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**
Once you have signed the CLA, please comment with `/check-cla` and confirm that the CLA check is green.

This is a standard procedure for many open source projects.

Please let us know if you have any questions.

We are very happy to have you join our growing community! If you're not yet a member, please consider joining our [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets) to meet other contributors and discuss new opportunities with the core team.

2023-10-05 09:03 UTC, yesbhautik commented
/check-cla

2023-10-12 13:33 UTC, cwarnermm requested changes
Thanks, @yesbhautik. Can you please remove the erroneous ``]`` visible in the generated preview. 
![image](https://github.com/mattermost/docs/assets/74422101/117faeea-391e-4f81-b791-e36e7a8fa9e8)

2023-10-12 13:35 UTC, yesbhautik commented
Sure.

2023-10-16 13:19 UTC, cwarnermm approved these changes

2023-10-16 13:19 UTC, merged