Updated proxy guidelines & added NGINX/TLS to nav
mattermost/docs pull request #6781
Opened 2023-11-13 17:27 UTC by cwarnermm

Also transitioned the deploy FAQ content into a common/shared page visible via: Ubuntu, RHEL, and Tarball deploy pages.

2023-12-04 15:26 UTC, nab-77 requested changes

2023-12-04 15:26 UTC, nab-77 commented on source/install/setup-nginx-proxy.rst
> +Set up an NGINX proxy
Possible to apply the new CSS/theme as per other install docs?

2023-12-05 17:33 UTC, coltoneshaw commented on source/install/setup-nginx-proxy.rst
> +.. include:: install-nginx.rst
I think it's on deck to redo the nginx install docs, so that could be a good area for this. I'd +1 neil here. But not needed for this PR

2023-12-05 17:34 UTC, coltoneshaw commented on source/install/common-deploy-faq.rst
> +  - We recommend the `Mattermost Omnibus install method </install/installing-mattermost-omnibus.html>`__ over the tarball if you are running the Mattermost Server and database a single system as this
This shouldn't show on RHEL install docs

2023-12-05 18:43 UTC, coltoneshaw commented
@cwarnermm - I think this is good! I do think we'll have FAQs per OS at some point, but for now merging is great.

2023-12-05 18:54 UTC, coltoneshaw approved these changes
lgtm

2023-12-15 13:39 UTC, merged