Updated reference architectures to scale Mattermost
mattermost/docs pull request #6941
Opened 2024-02-23 16:03 UTC by cwarnermm

Outstanding work:
- update architecture diagram (Carrie)
- expand available reference architectures section to explain what user count means (Neil B)
- expand load testing section (Neil B)
- populate Azure & GCP instance data for each scale page (Neil B)
- identify best place to link out to lifecycle/compatibility docs pages (Neil B)
- scale to 100 users: add additional considerations, if applicable (Neil B)

2024-02-27 14:13 UTC, cwarnermm commented
@agarciamontoro @isacikgoz @agnivade - Are you open to helping with the outstanding action items identified in the PR summary, please? Specifically, populating Azure & GCP instance data for each scale page, expanding on the load testing section, and suggesting any additional considerations for scaling up to 100 users?

2024-02-28 12:18 UTC, nab-77 requested changes
@cwarnermm first round of updates. This is a great layout. Thank you so much!

2024-02-28 14:51 UTC, cwarnermm commented on source/scale/scaling-for-enterprise.rst
> +[Neil] Lay out what we did in testing these archs (specifically which version of MM was used in the tests, when we plan to publish updated lists etc).
@nab-77 - I've provided editorial feedback on this section. Please review to ensure that your original intent is clearly communicated.

2024-02-29 16:11 UTC, agarciamontoro requested changes
Thank you for this, @cwarnermm and @nab-77! I left some comments inline about specific things, but here are some more general comments:

#### Notes on the diagram
- The first Mobile App Experience block says "Chrome Native app" instead of "Android native app"
- I'm not sure what the Authentication client, Authentication provider and Data Management Service entries mean in the Mattermost Server block.

#### Azure / GCP
We have not tested anything on Azure nor GCP. My recommendation is to remove those altogether. If we **need** to have them listed, I can look for similarly-speced instances in those services, but we'll have to add a big disclaimer stating that those are not tested.

#### Testing methodology and updates
I'm not sure how much information we want there, and how specific, but I think we could add some more things that can be interesting:
- No ElasticSearch was used
- No job servers were used
- All tests with more than one app node had an nginx running in front of them 
- Some more info on the DB:
  - We used Postgres v14
  - The initial database looked like:
    - Posts count: ~100 million
    - Users count: ~3000
    - Teams count: 20
    - Channels count: ~720000

2024-02-29 16:11 UTC, agarciamontoro commented on source/scale/scaling-for-enterprise.rst
> +Mattermost provides a set of tools written in Go to help profiling Mattermost under heavy load, simulating real-world usage of a server installation at scale. The `Mattermost Load Test Tools <https:/
We usually refer to the tool in singular, but 2/5.

2024-02-29 16:11 UTC, agarciamontoro commented on source/scale/scaling-for-enterprise.rst
> +Visit the `Mattermost Load Test Tools <https://github.com/mattermost/mattermost-load-test-ng/tree/master/docs>`__ documentation on GitHub for details on getting started with the tools, and visit `GDo
`GDoc` reads like Google Docs to me. I also usually link to https://pkg.go.dev/github.com/mattermost/mattermost-load-test-ng directly, not godoc.

2024-02-29 19:22 UTC, cwarnermm commented on source/scale/estimated-storage-per-user-per-month.rst
> + - Heaviest utilization comes from teams uploading a high number of large files into Mattermost on a regular basis. Examples include creative teams who share and store artwork and media with tags and
@nab-77 -- Thoughts?

2024-02-29 19:22 UTC, cwarnermm commented on source/scale/scale-to-1000-users.rst
> ++------------------------+----------+------------------+----------------+------------------+--------------------+------------------+
FYI @nab-77 ^

2024-02-29 19:31 UTC, cwarnermm commented
@nab-77 - Regarding @agarciamontoro's feedback: "We have not tested anything on Azure nor GCP. My recommendation is to remove those altogether. If we need to have them listed, I can look for similarly-speced instances in those services, but we'll have to add a big disclaimer stating that those are not tested." -- how do we want to proceed via docs? Remove these columns?

2024-03-01 17:17 UTC, agarciamontoro commented on source/scale/scale-to-70000-users.rst
> ++------------------------+----------+------------------+----------------+------------------+
```suggestion
+------------------------+----------+------------------+----------------+------------------+
| **Resource Type**      | **vCPU** | **Memory (GiB)** | **# of Nodes** | **AWS Instance** |
+========================+==========+==================+================+==================+
| Mattermost Application | 16       | 32               | 4              | c6i.4xlarge       |
+------------------------+----------+------------------+----------------+------------------+
| RDS Writer             | 16       | 128              | 1              | db.r6g.4xlarge    |
+------------------------+----------+------------------+----------------+------------------+
| RDS Reader             | 16       | 128              | 4              | db.r6g.4xlarge    |
+------------------------+----------+------------------+----------------+------------------+
```

2024-03-01 17:17 UTC, agarciamontoro commented on source/scale/scale-to-79000-users.rst
> ++------------------------+----------+------------------+----------------+------------------+
```suggestion
+------------------------+----------+------------------+----------------+------------------+
| **Resource Type**      | **vCPU** | **Memory (GiB)** | **# of Nodes** | **AWS Instance** |
+========================+==========+==================+================+==================+
| Mattermost Application | 16       | 32               | 5              | c6i.4xlarge       |
+------------------------+----------+------------------+----------------+------------------+
| RDS Writer             | 16       | 128              | 1              | db.r6g.4xlarge    |
+------------------------+----------+------------------+----------------+------------------+
| RDS Reader             | 16       | 128              | 4              | db.r6g.4xlarge    |
+------------------------+----------+------------------+----------------+------------------+
```

2024-03-01 17:18 UTC, agarciamontoro commented on source/scale/scale-to-88000-users.rst
> ++------------------------+----------+------------------+----------------+------------------+
```suggestion
+------------------------+----------+------------------+----------------+------------------+
| **Resource Type**      | **vCPU** | **Memory (GiB)** | **# of Nodes** | **AWS Instance** |
+========================+==========+==================+================+==================+
| Mattermost Application | 16       | 32               | 6              | c6i.4xlarge       |
+------------------------+----------+------------------+----------------+------------------+
| RDS Writer             | 16       | 128              | 1              | db.r6g.4xlarge    |
+------------------------+----------+------------------+----------------+------------------+
| RDS Reader             | 16       | 128              | 4              | db.r6g.4xlarge    |
+------------------------+----------+------------------+----------------+------------------+
```

2024-03-01 17:39 UTC, cwarnermm commented on source/scale/scaling-for-enterprise.rst
> +Full testing methodology, configuration, and setup is available. Sign up at `Mattermost Community <https://community.mattermost.com/>`__ and join the `Developers: Performance channel <https://communi
I believe the intention is that users interested in accessing details on the full testing methodology need to join the Mattermost Community Server and join the Performance channel to do so. @nab-77 - Is my understanding correct?

2024-03-01 17:43 UTC, agarciamontoro approved these changes
I have to log off for the day, so approving now to unblock. I'll leave the unaddressed comment to you both :) Thanks!

2024-03-01 17:49 UTC, merged

2024-03-01 18:47 UTC, nab-77 commented on source/scale/scaling-for-enterprise.rst
> +Full testing methodology, configuration, and setup is available. Sign up at `Mattermost Community <https://community.mattermost.com/>`__ and join the `Developers: Performance channel <https://communi
Correct @cwarnermm

2024-03-01 18:49 UTC, nab-77 commented
Great first pass team. v2 will take this to the next level.