Deprecated
mattermost/docs pull request #7014
Opened 2024-03-28 18:42 UTC by cwarnermm

Documentation for: https://mattermost.atlassian.net/browse/MM-57106

Deprecated the following HA config settings: MaxIdleConns, MaxIdleConnsPerHost, and IdleConnTimeoutMill…iseconds. Also removed multiple deprecated settings from telemetry docs documented erroneously.

2024-04-03 10:15 UTC, hanzei requested changes
On question regarding the formatting in `source/configure/deprecated-configuration-settings.rst`

2024-04-03 10:15 UTC, hanzei commented on source/configure/deprecated-configuration-settings.rst
> ++-----------------------------------------------------------------+------------------------------------------------------------------------+
The formatting is different to the other deprecated settings in the file. Is that intended?

2024-04-04 08:24 UTC, hanzei approved these changes

2024-04-04 08:24 UTC, hanzei commented on source/configure/deprecated-configuration-settings.rst
> ++-----------------------------------------------------------------+------------------------------------------------------------------------+
The only existing one I could find is `Enable publicly-shared boards` (https://github.com/mattermost/docs/blob/deprecate-legacy-configs/source/configure/deprecated-configuration-settings.rst#enable-publicly-shared-boards).

I'm 0/5 on what format to use. 1/5 that it looks a bit inconsistent to use different formats.

2024-04-04 13:20 UTC, cwarnermm commented
Agreed that the inconsistency isn't ideal; however, resources are limited and consistency on a deprecation page isn't a priority at this time.

2024-04-04 13:48 UTC, merged