Added max payload size config setting
mattermost/docs pull request #7127
Opened 2024-05-13 19:23 UTC by cwarnermm

https://github.com/mattermost/mattermost/pull/26651

2024-05-13 21:03 UTC, cwarnermm commented
@harshilsharma63 - Can you tell me a bit more about what this config setting does and why an admin might want to adjust the value?

2024-05-14 04:50 UTC, harshilsharma63 requested changes

2024-05-14 04:50 UTC, harshilsharma63 commented on source/configure/file-storage-configuration-settings.rst
> +  :description: The payload size, in bytes, of API endpoints passing in arrays. Default is 300000.
```suggestion
  :description: The maximum payload size in bytes for all APIs except APIs that receive a file as an input, for example, the upload attachment API or the API to upload a custom emoji. Default is 300000.
```

2024-05-14 04:50 UTC, harshilsharma63 commented on source/configure/file-storage-configuration-settings.rst
> +  :description: The payload size, in bytes, of API endpoints passing in arrays. Default is 300000.
@cwarnermm I've provided a text suggestion. Its not applicable to only arrays, but rather to all APIs except those that receive a file.

2024-05-14 13:55 UTC, harshilsharma63 approved these changes

2024-05-14 17:18 UTC, merged