Add FAQ to the mysql deprecation
mattermost/docs pull request #7299
Opened 2024-07-24 18:06 UTC by isacikgoz

#### Summary
To kick this effort off, I'm creating the PR so that anyone can also contribute from here.

2024-07-26 15:48 UTC, cwarnermm commented on source/deploy/postgres-migration.rst
> +===
```suggestion
----
```

2024-07-26 15:48 UTC, cwarnermm commented on source/deploy/postgres-migration.rst
> +FAQ
```suggestion
Frequently asked questions
```

2024-07-26 15:49 UTC, cwarnermm commented on source/deploy/postgres-migration.rst
> +----
```suggestion
------------------------------
```

2024-09-13 15:35 UTC, isacikgoz commented
@cwarnermm gentle ping for the editorial review :) Also please LMK if this is okay to merge @coltoneshaw @nab-77. I have other PRs incoming :)

2024-09-13 15:36 UTC, cwarnermm commented
@isacikgoz - I haven't yet contributed the updates noted in the PR summary above. Wondering if your updates included those or if they're still outstanding? I'm open to moving forward with this PR and adding any outstanding details in a future revision.

2024-09-13 15:39 UTC, cwarnermm requested changes
Please update the RST syntax specific to section titles as noted inline.

2024-09-13 15:39 UTC, cwarnermm commented on source/deploy/postgres-migration.rst
> +===============
A double-underline is reserved for the top page heading. Subsequent headings are denoted as follows:

- H2: ``------``
- H3: ``~~~~~~``
- H4: ``^^^^^^``
- H5: ``::::::``

2024-09-13 15:44 UTC, isacikgoz commented
Oh @cwarnermm I haven't seen your additions 😅 

> Migrating a Bitnami install (defaults to MySQL) requires Mattermost binary transition from TE to E0 & custom DB migration effort.

I'll take a look into that, but we can add that in the future.

> No checks for whether –migrations-dir is provided. –mattermost-version is required if not provided.

I'll add this to the next doc update. It's very specific to automated process.

An the rest is done in this PR.

2024-09-16 12:52 UTC, cwarnermm approved these changes
Thanks, @isacikgoz!

2024-09-16 13:28 UTC, merged