Improve Copilot + local AI setup instructions
mattermost/docs pull request #7413
Opened 2024-09-18 19:38 UTC by azigler

I noticed [this comment from a user](https://github.com/mattermost/mattermost-plugin-ai/issues/143#issuecomment-2358807158) that had trouble configuring Copilot with Ollama and realized that the documentation instructions do not include the specific URL instructions to access the OpenAI-compatible API. This PR clarifies that instruction, in line with what's taught in [the Academy course](https://academy.mattermost.com/p/new-mattermost-copilot-multi-llm-setup-usage).

2024-09-18 19:40 UTC, cwarnermm approved these changes
Thank you, @azigler!

2024-09-18 19:40 UTC, cwarnermm commented on source/configure/enable-copilot.rst
> +  3. Enter the URL to your AI service from your Mattermost deployment in the **API URL** field. Be sure to include the port, and append `/v1` to the end of the URL. (e.g., `http://localhost:11434/v1`
```suggestion
  3. Enter the URL to your AI service from your Mattermost deployment in the **API URL** field. Be sure to include the port, and append ``/v1`` to the end of the URL. (e.g., ``http://localhost:11434/v1`` for Ollama)
```

2024-09-18 19:44 UTC, azigler commented
@crspeller Should we include a recommendation for disabling tools? Is that a broad recommendation? If so, should we revisit the option and it's default setting? As a minor note, it's a bit confusing that the field is "disable" and has a true/false (which means the radio toggle is semantically opposite from the end result, which might confuse users). What about "Enable Tools" and it has a default setting to whatever you think is most appropriate?

2024-10-02 20:09 UTC, cwarnermm commented
Friendly reminder that this docs PR will benefit from your review, @crspeller.

2024-10-03 17:55 UTC, crspeller requested changes

2024-10-03 17:55 UTC, crspeller commented on source/configure/enable-copilot.rst
> +  3. Enter the URL to your AI service from your Mattermost deployment in the **API URL** field. Be sure to include the port, and append ``/v1`` to the end of the URL. (e.g., ``http://localhost:11434/
The instruction to add `/v1` is Ollama specific not a general instruction for all OpenAI compatable APIs. I don't think that is clear here.

2024-10-09 17:24 UTC, cwarnermm commented
@azigler - Are you open to adding a direct link from our LLM admin docs to LLM setup training via Academy? You can use https://github.com/mattermost/docs/pull/7465 as a reference to do so.

2024-10-09 19:07 UTC, azigler commented
@crspeller Clarified that.

@cwarnermm Added that!

Good to go! 👍

2024-10-10 12:21 UTC, crspeller approved these changes

2024-10-10 12:58 UTC, merged