Added upgrade & maintenance guidance for plugins
mattermost/docs pull request #7554
Opened 2024-11-05 18:59 UTC by cwarnermm

2024-11-06 22:25 UTC, marianunez approved these changes

2024-11-06 22:25 UTC, marianunez commented on source/guides/integrate-and-extend.rst
> +  - Manually placing Mattermost integration files in the ``/plugins`` directory isn't recommended.
Maybe we can include that this is planned to be deprecated in future release. We can link @lieut-data forum post announcement https://forum.mattermost.com/t/deprecation-notice-manual-plugin-deployment/21192

2024-11-06 22:25 UTC, marianunez commented on source/integrate/github-interoperability.rst
> +  - Use the System Console, REST API, or in-product Marketplace to manage this integration. Manually placing Mattermost integration files in the ``/plugins`` directory isn't recommended.
```suggestion
  - Use the System Console, REST API, or in-product Marketplace to manage this integration. Manually placing Mattermost integration files in the ``/plugins`` directory isn't recommended and will be [deprecated in future versions](https://forum.mattermost.com/t/deprecation-notice-manual-plugin-deployment/21192).
```

2024-11-07 14:21 UTC, cwarnermm commented on source/guides/integrate-and-extend.rst
> +  - Manually placing Mattermost integration files in the ``/plugins`` directory isn't recommended.
```suggestion
  - Manually placing Mattermost integration files in the ``/plugins`` directory isn't recommended and will be `deprecated in future versions <https://forum.mattermost.com/t/deprecation-notice-manual-plugin-deployment/21192>`_.
```

2024-11-08 19:38 UTC, lieut-data requested changes
Thanks, Carrie -- a few thoughts below.

2024-11-08 19:38 UTC, lieut-data commented on source/guides/integrate-and-extend.rst
> +  - We also strongly recommend testing integration updates in a staging environment before deploying to production, and regularly backing up integrations.
Propose a simpler summary for all of these:
> Installed plugins are persisted to the configured file store and unpacked on server startup. It's imperative that your file store be accessible to the server immediately on startup. If using a shared filesystem, ensure the mount completes successfully before starting the server.

2024-11-08 19:38 UTC, lieut-data commented on source/integrate/github-interoperability.rst
> +
From here on out, I'd propose reverting all the changes. We don't need to duplicate this on a per-plugin basis, IMO.

2024-11-08 21:00 UTC, cwarnermm commented
Thanks, @lieut-data! I've incorporated your feedback in my latest commit.

2024-11-12 14:02 UTC, merged