New page for push notification health targets
mattermost/docs pull request #7640
Opened 2024-12-03 17:24 UTC by cwarnermm

Incorporated [Engineering thought leadership and guidance](https://mattermost.atlassian.net/wiki/spaces/ICU/pages/3111026690/Push+Notification+Health+Targets) into the product docs.

2024-12-04 21:43 UTC, cwarnermm commented on source/scale/push-notification-health-targets.rst
> +When using the `Mattermost Notification Health <https://grafana.com/grafana/dashboards/21305-mattermost-notification-health>`_ Grafana dashboard to track different types of notifications sent from Ma
```suggestion
When using the `Mattermost Notification Health <https://grafana.com/grafana/dashboards/21305-mattermost-notification-health>`_ Grafana dashboard to track different types of notifications sent from Mattermost, we recommend adhering to the following mobile push notification health targets to ensure a performant production deployment of Mattermost.
```

2024-12-05 11:28 UTC, larkox requested changes
Great work! Just two small things to rephrase.

2024-12-05 11:28 UTC, larkox commented on source/scale/push-notification-health-targets.rst
> +The **Push Proxy Delivery Rate** panel indicates the percentage of push notifications that have been successfully delivered to the endpoints (i.e., mobile devices) out of the total number of push not
Not exactly the devices. It is more about the Push Notification Service (Apple Push Notification service (APNs) or Firebase Cloud Messaging (FCM)).

2024-12-05 11:28 UTC, larkox commented on source/scale/push-notification-health-targets.rst
> +The **Push Notifications Not Sent Distribution** panel helps admins ensure the robustness and reliability of the push notification system by providing detailed insights into the specific reasons for
Not really delivery failures. In this context, it is not a failure the notification was not sent. It is expected that the notification was not sent, and this tell us the reason why that is expected.

For example, a notification is not sent, if the channel is muted.

2024-12-05 14:15 UTC, cwarnermm commented
Great feedback, @larkox, thank you! I've incorporated your changes in my latest commit.

2024-12-05 14:43 UTC, merged